// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsProductNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_PRODUCT_NOT_FOUND.String() && e.Code == 404
}

func ErrorProductNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_PRODUCT_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsCategoryNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CATEGORY_NOT_FOUND.String() && e.Code == 404
}

func ErrorCategoryNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_CATEGORY_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsEventNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_EVENT_NOT_FOUND.String() && e.Code == 404
}

func ErrorEventNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_EVENT_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsInsufficientStock(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INSUFFICIENT_STOCK.String() && e.Code == 409
}

func ErrorInsufficientStock(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_INSUFFICIENT_STOCK.String(), fmt.Sprintf(format, args...))
}

func IsProductStatusInvalid(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_PRODUCT_STATUS_INVALID.String() && e.Code == 400
}

func ErrorProductStatusInvalid(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_PRODUCT_STATUS_INVALID.String(), fmt.Sprintf(format, args...))
}

func IsCategoryHasProducts(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CATEGORY_HAS_PRODUCTS.String() && e.Code == 409
}

func ErrorCategoryHasProducts(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_CATEGORY_HAS_PRODUCTS.String(), fmt.Sprintf(format, args...))
}

func IsShippingAddressNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_SHIPPING_ADDRESS_NOT_FOUND.String() && e.Code == 404
}

func ErrorShippingAddressNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_SHIPPING_ADDRESS_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}
