// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.1
// source: api/mall/v1/mall.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationMallCreateCategory = "/api.mall.v1.Mall/CreateCategory"
const OperationMallCreateEvent = "/api.mall.v1.Mall/CreateEvent"
const OperationMallCreateProduct = "/api.mall.v1.Mall/CreateProduct"
const OperationMallDeleteCategory = "/api.mall.v1.Mall/DeleteCategory"
const OperationMallDeleteEvent = "/api.mall.v1.Mall/DeleteEvent"
const OperationMallDeleteProduct = "/api.mall.v1.Mall/DeleteProduct"
const OperationMallGetEvent = "/api.mall.v1.Mall/GetEvent"
const OperationMallGetProduct = "/api.mall.v1.Mall/GetProduct"
const OperationMallListCategories = "/api.mall.v1.Mall/ListCategories"
const OperationMallListEvents = "/api.mall.v1.Mall/ListEvents"
const OperationMallListProducts = "/api.mall.v1.Mall/ListProducts"
const OperationMallUpdateCategory = "/api.mall.v1.Mall/UpdateCategory"
const OperationMallUpdateEvent = "/api.mall.v1.Mall/UpdateEvent"
const OperationMallUpdateEventStatus = "/api.mall.v1.Mall/UpdateEventStatus"
const OperationMallUpdateProduct = "/api.mall.v1.Mall/UpdateProduct"
const OperationMallUpdateProductStatus = "/api.mall.v1.Mall/UpdateProductStatus"

type MallHTTPServer interface {
	// CreateCategory Categories
	CreateCategory(context.Context, *CreateCategoryRequest) (*Category, error)
	// CreateEvent Events
	CreateEvent(context.Context, *CreateEventRequest) (*Event, error)
	// CreateProduct Products
	CreateProduct(context.Context, *CreateProductRequest) (*Product, error)
	DeleteCategory(context.Context, *DeleteCategoryRequest) (*DeleteCategoryReply, error)
	DeleteEvent(context.Context, *DeleteEventRequest) (*DeleteEventReply, error)
	DeleteProduct(context.Context, *DeleteProductRequest) (*DeleteProductReply, error)
	GetEvent(context.Context, *GetEventRequest) (*Event, error)
	GetProduct(context.Context, *GetProductRequest) (*Product, error)
	ListCategories(context.Context, *ListCategoriesRequest) (*ListCategoriesReply, error)
	ListEvents(context.Context, *ListEventsRequest) (*ListEventsReply, error)
	ListProducts(context.Context, *ListProductsRequest) (*ListProductsReply, error)
	UpdateCategory(context.Context, *UpdateCategoryRequest) (*Category, error)
	UpdateEvent(context.Context, *UpdateEventRequest) (*Event, error)
	UpdateEventStatus(context.Context, *UpdateEventStatusRequest) (*UpdateEventStatusReply, error)
	UpdateProduct(context.Context, *UpdateProductRequest) (*Product, error)
	UpdateProductStatus(context.Context, *UpdateProductStatusRequest) (*UpdateProductStatusReply, error)
}

func RegisterMallHTTPServer(s *http.Server, srv MallHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/categories", _Mall_CreateCategory0_HTTP_Handler(srv))
	r.GET("/v1/categories", _Mall_ListCategories0_HTTP_Handler(srv))
	r.PUT("/v1/categories/{id}", _Mall_UpdateCategory0_HTTP_Handler(srv))
	r.DELETE("/v1/categories/{id}", _Mall_DeleteCategory0_HTTP_Handler(srv))
	r.POST("/v1/products", _Mall_CreateProduct0_HTTP_Handler(srv))
	r.GET("/v1/products/{id}", _Mall_GetProduct0_HTTP_Handler(srv))
	r.GET("/v1/products", _Mall_ListProducts0_HTTP_Handler(srv))
	r.PUT("/v1/products/{id}", _Mall_UpdateProduct0_HTTP_Handler(srv))
	r.PATCH("/v1/products/{id}/status", _Mall_UpdateProductStatus0_HTTP_Handler(srv))
	r.DELETE("/v1/products/{id}", _Mall_DeleteProduct0_HTTP_Handler(srv))
	r.POST("/v1/events", _Mall_CreateEvent0_HTTP_Handler(srv))
	r.GET("/v1/events/{id}", _Mall_GetEvent0_HTTP_Handler(srv))
	r.GET("/v1/events", _Mall_ListEvents0_HTTP_Handler(srv))
	r.PUT("/v1/events/{id}", _Mall_UpdateEvent0_HTTP_Handler(srv))
	r.PATCH("/v1/events/{id}/status", _Mall_UpdateEventStatus0_HTTP_Handler(srv))
	r.DELETE("/v1/events/{id}", _Mall_DeleteEvent0_HTTP_Handler(srv))
}

func _Mall_CreateCategory0_HTTP_Handler(srv MallHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateCategoryRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMallCreateCategory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateCategory(ctx, req.(*CreateCategoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Category)
		return ctx.Result(200, reply)
	}
}

func _Mall_ListCategories0_HTTP_Handler(srv MallHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCategoriesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMallListCategories)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCategories(ctx, req.(*ListCategoriesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListCategoriesReply)
		return ctx.Result(200, reply)
	}
}

func _Mall_UpdateCategory0_HTTP_Handler(srv MallHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateCategoryRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMallUpdateCategory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateCategory(ctx, req.(*UpdateCategoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Category)
		return ctx.Result(200, reply)
	}
}

func _Mall_DeleteCategory0_HTTP_Handler(srv MallHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteCategoryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMallDeleteCategory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteCategory(ctx, req.(*DeleteCategoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteCategoryReply)
		return ctx.Result(200, reply)
	}
}

func _Mall_CreateProduct0_HTTP_Handler(srv MallHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateProductRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMallCreateProduct)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateProduct(ctx, req.(*CreateProductRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Product)
		return ctx.Result(200, reply)
	}
}

func _Mall_GetProduct0_HTTP_Handler(srv MallHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProductRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMallGetProduct)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetProduct(ctx, req.(*GetProductRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Product)
		return ctx.Result(200, reply)
	}
}

func _Mall_ListProducts0_HTTP_Handler(srv MallHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListProductsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMallListProducts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListProducts(ctx, req.(*ListProductsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProductsReply)
		return ctx.Result(200, reply)
	}
}

func _Mall_UpdateProduct0_HTTP_Handler(srv MallHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateProductRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMallUpdateProduct)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateProduct(ctx, req.(*UpdateProductRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Product)
		return ctx.Result(200, reply)
	}
}

func _Mall_UpdateProductStatus0_HTTP_Handler(srv MallHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateProductStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMallUpdateProductStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateProductStatus(ctx, req.(*UpdateProductStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateProductStatusReply)
		return ctx.Result(200, reply)
	}
}

func _Mall_DeleteProduct0_HTTP_Handler(srv MallHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteProductRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMallDeleteProduct)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteProduct(ctx, req.(*DeleteProductRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteProductReply)
		return ctx.Result(200, reply)
	}
}

func _Mall_CreateEvent0_HTTP_Handler(srv MallHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateEventRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMallCreateEvent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateEvent(ctx, req.(*CreateEventRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Event)
		return ctx.Result(200, reply)
	}
}

func _Mall_GetEvent0_HTTP_Handler(srv MallHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetEventRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMallGetEvent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetEvent(ctx, req.(*GetEventRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Event)
		return ctx.Result(200, reply)
	}
}

func _Mall_ListEvents0_HTTP_Handler(srv MallHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListEventsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMallListEvents)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListEvents(ctx, req.(*ListEventsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListEventsReply)
		return ctx.Result(200, reply)
	}
}

func _Mall_UpdateEvent0_HTTP_Handler(srv MallHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateEventRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMallUpdateEvent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateEvent(ctx, req.(*UpdateEventRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Event)
		return ctx.Result(200, reply)
	}
}

func _Mall_UpdateEventStatus0_HTTP_Handler(srv MallHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateEventStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMallUpdateEventStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateEventStatus(ctx, req.(*UpdateEventStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateEventStatusReply)
		return ctx.Result(200, reply)
	}
}

func _Mall_DeleteEvent0_HTTP_Handler(srv MallHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteEventRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMallDeleteEvent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteEvent(ctx, req.(*DeleteEventRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteEventReply)
		return ctx.Result(200, reply)
	}
}

type MallHTTPClient interface {
	// CreateCategory Categories
	CreateCategory(ctx context.Context, req *CreateCategoryRequest, opts ...http.CallOption) (rsp *Category, err error)
	// CreateEvent Events
	CreateEvent(ctx context.Context, req *CreateEventRequest, opts ...http.CallOption) (rsp *Event, err error)
	// CreateProduct Products
	CreateProduct(ctx context.Context, req *CreateProductRequest, opts ...http.CallOption) (rsp *Product, err error)
	DeleteCategory(ctx context.Context, req *DeleteCategoryRequest, opts ...http.CallOption) (rsp *DeleteCategoryReply, err error)
	DeleteEvent(ctx context.Context, req *DeleteEventRequest, opts ...http.CallOption) (rsp *DeleteEventReply, err error)
	DeleteProduct(ctx context.Context, req *DeleteProductRequest, opts ...http.CallOption) (rsp *DeleteProductReply, err error)
	GetEvent(ctx context.Context, req *GetEventRequest, opts ...http.CallOption) (rsp *Event, err error)
	GetProduct(ctx context.Context, req *GetProductRequest, opts ...http.CallOption) (rsp *Product, err error)
	ListCategories(ctx context.Context, req *ListCategoriesRequest, opts ...http.CallOption) (rsp *ListCategoriesReply, err error)
	ListEvents(ctx context.Context, req *ListEventsRequest, opts ...http.CallOption) (rsp *ListEventsReply, err error)
	ListProducts(ctx context.Context, req *ListProductsRequest, opts ...http.CallOption) (rsp *ListProductsReply, err error)
	UpdateCategory(ctx context.Context, req *UpdateCategoryRequest, opts ...http.CallOption) (rsp *Category, err error)
	UpdateEvent(ctx context.Context, req *UpdateEventRequest, opts ...http.CallOption) (rsp *Event, err error)
	UpdateEventStatus(ctx context.Context, req *UpdateEventStatusRequest, opts ...http.CallOption) (rsp *UpdateEventStatusReply, err error)
	UpdateProduct(ctx context.Context, req *UpdateProductRequest, opts ...http.CallOption) (rsp *Product, err error)
	UpdateProductStatus(ctx context.Context, req *UpdateProductStatusRequest, opts ...http.CallOption) (rsp *UpdateProductStatusReply, err error)
}

type MallHTTPClientImpl struct {
	cc *http.Client
}

func NewMallHTTPClient(client *http.Client) MallHTTPClient {
	return &MallHTTPClientImpl{client}
}

// CreateCategory Categories
func (c *MallHTTPClientImpl) CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...http.CallOption) (*Category, error) {
	var out Category
	pattern := "/v1/categories"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMallCreateCategory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateEvent Events
func (c *MallHTTPClientImpl) CreateEvent(ctx context.Context, in *CreateEventRequest, opts ...http.CallOption) (*Event, error) {
	var out Event
	pattern := "/v1/events"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMallCreateEvent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateProduct Products
func (c *MallHTTPClientImpl) CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...http.CallOption) (*Product, error) {
	var out Product
	pattern := "/v1/products"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMallCreateProduct))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MallHTTPClientImpl) DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...http.CallOption) (*DeleteCategoryReply, error) {
	var out DeleteCategoryReply
	pattern := "/v1/categories/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMallDeleteCategory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MallHTTPClientImpl) DeleteEvent(ctx context.Context, in *DeleteEventRequest, opts ...http.CallOption) (*DeleteEventReply, error) {
	var out DeleteEventReply
	pattern := "/v1/events/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMallDeleteEvent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MallHTTPClientImpl) DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...http.CallOption) (*DeleteProductReply, error) {
	var out DeleteProductReply
	pattern := "/v1/products/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMallDeleteProduct))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MallHTTPClientImpl) GetEvent(ctx context.Context, in *GetEventRequest, opts ...http.CallOption) (*Event, error) {
	var out Event
	pattern := "/v1/events/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMallGetEvent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MallHTTPClientImpl) GetProduct(ctx context.Context, in *GetProductRequest, opts ...http.CallOption) (*Product, error) {
	var out Product
	pattern := "/v1/products/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMallGetProduct))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MallHTTPClientImpl) ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...http.CallOption) (*ListCategoriesReply, error) {
	var out ListCategoriesReply
	pattern := "/v1/categories"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMallListCategories))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MallHTTPClientImpl) ListEvents(ctx context.Context, in *ListEventsRequest, opts ...http.CallOption) (*ListEventsReply, error) {
	var out ListEventsReply
	pattern := "/v1/events"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMallListEvents))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MallHTTPClientImpl) ListProducts(ctx context.Context, in *ListProductsRequest, opts ...http.CallOption) (*ListProductsReply, error) {
	var out ListProductsReply
	pattern := "/v1/products"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMallListProducts))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MallHTTPClientImpl) UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...http.CallOption) (*Category, error) {
	var out Category
	pattern := "/v1/categories/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMallUpdateCategory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MallHTTPClientImpl) UpdateEvent(ctx context.Context, in *UpdateEventRequest, opts ...http.CallOption) (*Event, error) {
	var out Event
	pattern := "/v1/events/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMallUpdateEvent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MallHTTPClientImpl) UpdateEventStatus(ctx context.Context, in *UpdateEventStatusRequest, opts ...http.CallOption) (*UpdateEventStatusReply, error) {
	var out UpdateEventStatusReply
	pattern := "/v1/events/{id}/status"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMallUpdateEventStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MallHTTPClientImpl) UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...http.CallOption) (*Product, error) {
	var out Product
	pattern := "/v1/products/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMallUpdateProduct))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MallHTTPClientImpl) UpdateProductStatus(ctx context.Context, in *UpdateProductStatusRequest, opts ...http.CallOption) (*UpdateProductStatusReply, error) {
	var out UpdateProductStatusReply
	pattern := "/v1/products/{id}/status"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMallUpdateProductStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
