server:
  http:
    addr: 0.0.0.0:8000
    timeout: 10s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 10s
data:
  database:
    driver: postgres
    source: postgres://postgres:postgres@postgres:5432/ecommerce?sslmode=disable
  redis:
    addr: redis:6379
    network: tcp
    dial_timeout: 5s
    read_timeout: 0.2s
    write_timeout: 0.2s

auth:
  access_token_secret: ""
  access_token_timeout: 3600s
  refresh_token_secret: ""
  refresh_token_timeout: 86400s
  phone_secret: ""

snowflake:
  node_id: "${SNOWFLAKE_NODE_ID}"

trace:
  endpoint: http://otel-collector:4317

payment:
  order_payment_timeout: 30m
  prepay_lease_duration: 30s
  alipay:
    enabled: "${PAYMENT_ALIPAY_ENABLED}"
    app_id: "${ALIPAY_APP_ID}"
    private_key: "${ALIPAY_PRIVATE_KEY}"
    is_production: "${ALIPAY_IS_PRODUCTION}"
    app_cert_path: "${ALIPAY_APP_CERT_PATH}"
    alipay_public_cert_path: "${ALIPAY_PUBLIC_KEY_PATH}"
    alipay_root_cert_path: "${ALIPAY_ROOT_KEY_PATH}"
  wechat:
    enabled: "${PAYMENT_WECHAT_ENABLED}"
    app_id: "${WECHAT_APP_ID}"
    mch_id: "${WECHAT_MCH_ID}"
    api_key: "${WECHAT_API_KEY}"
    is_production: "${WECHAT_IS_PRODUCTION}"
  check_pay_job:
    initial_delay: 5s
    max_polls: 30
    poll_interval: 10s
