syntax = "proto3";
package kratos.api;

import "google/protobuf/duration.proto";

option go_package = "github.com/Dailiduzhou/simple-ecommerce/app/mall/internal/conf;conf";

message Bootstrap {
  Server server = 1;
  Data data = 2;
  Auth auth = 3;
  Snowflake snowflake = 4;
  Payment payment = 5;
}

message Snowflake {
  int32 node_id = 1;
}

message Auth {
  string access_token_secret = 1;
  google.protobuf.Duration access_token_timeout = 2;
  string refresh_token_secret = 3;
  google.protobuf.Duration refresh_token_timeout = 4;
  string phone_secret = 5;
}

message Server {
  message HTTP {
    string network = 1;
    string addr = 2;
    google.protobuf.Duration timeout = 3;
  }
  message GRPC {
    string network = 1;
    string addr = 2;
    google.protobuf.Duration timeout = 3;
  }
  HTTP http = 1;
  GRPC grpc = 2;
}

message Data {
  message Database {
    string driver = 1;
    string source = 2;
  }
  message Redis {
    string network = 1;
    string addr = 2;
    google.protobuf.Duration read_timeout = 3;
    google.protobuf.Duration write_timeout = 4;
    google.protobuf.Duration dial_timeout = 5;
  }
  Database database = 1;
  Redis redis = 2;
}

message Payment {
  Alipay alipay = 1;
  Wechat wechat = 2;
  CheckPayJob check_pay_job = 3;
}

message Alipay {
  string app_id = 1;
  string private_key = 2;
  bool is_production = 3;
  string app_cert_path = 4;
  string alipay_public_cert_path = 5;
  string alipay_root_cert_path = 6;
  bool enabled = 7;
}

message Wechat {
  string app_id = 1;
  string mch_id = 2;
  string api_key = 3;
  bool is_production = 4;
  bool enabled = 5;
}

message CheckPayJob {
  // 首次延迟多久开始轮询。
  google.protobuf.Duration initial_delay = 1;
  // 最大轮询次数。
  int32 max_polls = 2;
  // 每次轮询间隔。
  google.protobuf.Duration poll_interval = 3;
}
