// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Auth          *Auth                  `protobuf:"bytes,3,opt,name=auth,proto3" json:"auth,omitempty"`
	Snowflake     *Snowflake             `protobuf:"bytes,4,opt,name=snowflake,proto3" json:"snowflake,omitempty"`
	Payment       *Payment               `protobuf:"bytes,5,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *Bootstrap) GetSnowflake() *Snowflake {
	if x != nil {
		return x.Snowflake
	}
	return nil
}

func (x *Bootstrap) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

type Snowflake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snowflake) Reset() {
	*x = Snowflake{}
	mi := &file_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snowflake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snowflake) ProtoMessage() {}

func (x *Snowflake) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snowflake.ProtoReflect.Descriptor instead.
func (*Snowflake) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Snowflake) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type Auth struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AccessTokenSecret   string                 `protobuf:"bytes,1,opt,name=access_token_secret,json=accessTokenSecret,proto3" json:"access_token_secret,omitempty"`
	AccessTokenTimeout  *durationpb.Duration   `protobuf:"bytes,2,opt,name=access_token_timeout,json=accessTokenTimeout,proto3" json:"access_token_timeout,omitempty"`
	RefreshTokenSecret  string                 `protobuf:"bytes,3,opt,name=refresh_token_secret,json=refreshTokenSecret,proto3" json:"refresh_token_secret,omitempty"`
	RefreshTokenTimeout *durationpb.Duration   `protobuf:"bytes,4,opt,name=refresh_token_timeout,json=refreshTokenTimeout,proto3" json:"refresh_token_timeout,omitempty"`
	PhoneSecret         string                 `protobuf:"bytes,5,opt,name=phone_secret,json=phoneSecret,proto3" json:"phone_secret,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Auth) GetAccessTokenSecret() string {
	if x != nil {
		return x.AccessTokenSecret
	}
	return ""
}

func (x *Auth) GetAccessTokenTimeout() *durationpb.Duration {
	if x != nil {
		return x.AccessTokenTimeout
	}
	return nil
}

func (x *Auth) GetRefreshTokenSecret() string {
	if x != nil {
		return x.RefreshTokenSecret
	}
	return ""
}

func (x *Auth) GetRefreshTokenTimeout() *durationpb.Duration {
	if x != nil {
		return x.RefreshTokenTimeout
	}
	return nil
}

func (x *Auth) GetPhoneSecret() string {
	if x != nil {
		return x.PhoneSecret
	}
	return ""
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *Server_HTTP           `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Grpc          *Server_GRPC           `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *Data_Database         `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Redis         *Data_Redis            `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{4}
}

func (x *Data) GetDatabase() *Data_Database {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *Data) GetRedis() *Data_Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

type Payment struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Alipay              *Alipay                `protobuf:"bytes,1,opt,name=alipay,proto3" json:"alipay,omitempty"`
	Wechat              *Wechat                `protobuf:"bytes,2,opt,name=wechat,proto3" json:"wechat,omitempty"`
	CheckPayJob         *CheckPayJob           `protobuf:"bytes,3,opt,name=check_pay_job,json=checkPayJob,proto3" json:"check_pay_job,omitempty"`
	OrderPaymentTimeout *durationpb.Duration   `protobuf:"bytes,4,opt,name=order_payment_timeout,json=orderPaymentTimeout,proto3" json:"order_payment_timeout,omitempty"`
	PrepayLeaseDuration *durationpb.Duration   `protobuf:"bytes,5,opt,name=prepay_lease_duration,json=prepayLeaseDuration,proto3" json:"prepay_lease_duration,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{5}
}

func (x *Payment) GetAlipay() *Alipay {
	if x != nil {
		return x.Alipay
	}
	return nil
}

func (x *Payment) GetWechat() *Wechat {
	if x != nil {
		return x.Wechat
	}
	return nil
}

func (x *Payment) GetCheckPayJob() *CheckPayJob {
	if x != nil {
		return x.CheckPayJob
	}
	return nil
}

func (x *Payment) GetOrderPaymentTimeout() *durationpb.Duration {
	if x != nil {
		return x.OrderPaymentTimeout
	}
	return nil
}

func (x *Payment) GetPrepayLeaseDuration() *durationpb.Duration {
	if x != nil {
		return x.PrepayLeaseDuration
	}
	return nil
}

type Alipay struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AppId                string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	PrivateKey           string                 `protobuf:"bytes,2,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	IsProduction         bool                   `protobuf:"varint,3,opt,name=is_production,json=isProduction,proto3" json:"is_production,omitempty"`
	AppCertPath          string                 `protobuf:"bytes,4,opt,name=app_cert_path,json=appCertPath,proto3" json:"app_cert_path,omitempty"`
	AlipayPublicCertPath string                 `protobuf:"bytes,5,opt,name=alipay_public_cert_path,json=alipayPublicCertPath,proto3" json:"alipay_public_cert_path,omitempty"`
	AlipayRootCertPath   string                 `protobuf:"bytes,6,opt,name=alipay_root_cert_path,json=alipayRootCertPath,proto3" json:"alipay_root_cert_path,omitempty"`
	Enabled              bool                   `protobuf:"varint,7,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Alipay) Reset() {
	*x = Alipay{}
	mi := &file_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alipay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alipay) ProtoMessage() {}

func (x *Alipay) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alipay.ProtoReflect.Descriptor instead.
func (*Alipay) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{6}
}

func (x *Alipay) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *Alipay) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *Alipay) GetIsProduction() bool {
	if x != nil {
		return x.IsProduction
	}
	return false
}

func (x *Alipay) GetAppCertPath() string {
	if x != nil {
		return x.AppCertPath
	}
	return ""
}

func (x *Alipay) GetAlipayPublicCertPath() string {
	if x != nil {
		return x.AlipayPublicCertPath
	}
	return ""
}

func (x *Alipay) GetAlipayRootCertPath() string {
	if x != nil {
		return x.AlipayRootCertPath
	}
	return ""
}

func (x *Alipay) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type Wechat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	MchId         string                 `protobuf:"bytes,2,opt,name=mch_id,json=mchId,proto3" json:"mch_id,omitempty"`
	ApiKey        string                 `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	IsProduction  bool                   `protobuf:"varint,4,opt,name=is_production,json=isProduction,proto3" json:"is_production,omitempty"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wechat) Reset() {
	*x = Wechat{}
	mi := &file_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wechat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wechat) ProtoMessage() {}

func (x *Wechat) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wechat.ProtoReflect.Descriptor instead.
func (*Wechat) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{7}
}

func (x *Wechat) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *Wechat) GetMchId() string {
	if x != nil {
		return x.MchId
	}
	return ""
}

func (x *Wechat) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *Wechat) GetIsProduction() bool {
	if x != nil {
		return x.IsProduction
	}
	return false
}

func (x *Wechat) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type CheckPayJob struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 首次延迟多久开始轮询。
	InitialDelay *durationpb.Duration `protobuf:"bytes,1,opt,name=initial_delay,json=initialDelay,proto3" json:"initial_delay,omitempty"`
	// 最大轮询次数。
	MaxPolls int32 `protobuf:"varint,2,opt,name=max_polls,json=maxPolls,proto3" json:"max_polls,omitempty"`
	// 每次轮询间隔。
	PollInterval  *durationpb.Duration `protobuf:"bytes,3,opt,name=poll_interval,json=pollInterval,proto3" json:"poll_interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPayJob) Reset() {
	*x = CheckPayJob{}
	mi := &file_conf_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPayJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPayJob) ProtoMessage() {}

func (x *CheckPayJob) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPayJob.ProtoReflect.Descriptor instead.
func (*CheckPayJob) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{8}
}

func (x *CheckPayJob) GetInitialDelay() *durationpb.Duration {
	if x != nil {
		return x.InitialDelay
	}
	return nil
}

func (x *CheckPayJob) GetMaxPolls() int32 {
	if x != nil {
		return x.MaxPolls
	}
	return 0
}

func (x *CheckPayJob) GetPollInterval() *durationpb.Duration {
	if x != nil {
		return x.PollInterval
	}
	return nil
}

type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_conf_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_conf_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Data_Database struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Driver        string                 `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Database) Reset() {
	*x = Data_Database{}
	mi := &file_conf_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Database) ProtoMessage() {}

func (x *Data_Database) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Database.ProtoReflect.Descriptor instead.
func (*Data_Database) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Data_Database) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *Data_Database) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type Data_Redis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	ReadTimeout   *durationpb.Duration   `protobuf:"bytes,3,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	WriteTimeout  *durationpb.Duration   `protobuf:"bytes,4,opt,name=write_timeout,json=writeTimeout,proto3" json:"write_timeout,omitempty"`
	DialTimeout   *durationpb.Duration   `protobuf:"bytes,5,opt,name=dial_timeout,json=dialTimeout,proto3" json:"dial_timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Redis) Reset() {
	*x = Data_Redis{}
	mi := &file_conf_conf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Redis) ProtoMessage() {}

func (x *Data_Redis) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Redis.ProtoReflect.Descriptor instead.
func (*Data_Redis) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{4, 1}
}

func (x *Data_Redis) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Data_Redis) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Data_Redis) GetReadTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReadTimeout
	}
	return nil
}

func (x *Data_Redis) GetWriteTimeout() *durationpb.Duration {
	if x != nil {
		return x.WriteTimeout
	}
	return nil
}

func (x *Data_Redis) GetDialTimeout() *durationpb.Duration {
	if x != nil {
		return x.DialTimeout
	}
	return nil
}

var File_conf_conf_proto protoreflect.FileDescriptor

const file_conf_conf_proto_rawDesc = "" +
	"\n" +
	"\x0fconf/conf.proto\x12\n" +
	"kratos.api\x1a\x1egoogle/protobuf/duration.proto\"\xe7\x01\n" +
	"\tBootstrap\x12*\n" +
	"\x06server\x18\x01 \x01(\v2\x12.kratos.api.ServerR\x06server\x12$\n" +
	"\x04data\x18\x02 \x01(\v2\x10.kratos.api.DataR\x04data\x12$\n" +
	"\x04auth\x18\x03 \x01(\v2\x10.kratos.api.AuthR\x04auth\x123\n" +
	"\tsnowflake\x18\x04 \x01(\v2\x15.kratos.api.SnowflakeR\tsnowflake\x12-\n" +
	"\apayment\x18\x05 \x01(\v2\x13.kratos.api.PaymentR\apayment\"$\n" +
	"\tSnowflake\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\"\xa7\x02\n" +
	"\x04Auth\x12.\n" +
	"\x13access_token_secret\x18\x01 \x01(\tR\x11accessTokenSecret\x12K\n" +
	"\x14access_token_timeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x12accessTokenTimeout\x120\n" +
	"\x14refresh_token_secret\x18\x03 \x01(\tR\x12refreshTokenSecret\x12M\n" +
	"\x15refresh_token_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x13refreshTokenTimeout\x12!\n" +
	"\fphone_secret\x18\x05 \x01(\tR\vphoneSecret\"\xb8\x02\n" +
	"\x06Server\x12+\n" +
	"\x04http\x18\x01 \x01(\v2\x17.kratos.api.Server.HTTPR\x04http\x12+\n" +
	"\x04grpc\x18\x02 \x01(\v2\x17.kratos.api.Server.GRPCR\x04grpc\x1ai\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1ai\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\x9b\x03\n" +
	"\x04Data\x125\n" +
	"\bdatabase\x18\x01 \x01(\v2\x19.kratos.api.Data.DatabaseR\bdatabase\x12,\n" +
	"\x05redis\x18\x02 \x01(\v2\x16.kratos.api.Data.RedisR\x05redis\x1a:\n" +
	"\bDatabase\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x1a\xf1\x01\n" +
	"\x05Redis\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12<\n" +
	"\fread_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\vreadTimeout\x12>\n" +
	"\rwrite_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\fwriteTimeout\x12<\n" +
	"\fdial_timeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\vdialTimeout\"\xbc\x02\n" +
	"\aPayment\x12*\n" +
	"\x06alipay\x18\x01 \x01(\v2\x12.kratos.api.AlipayR\x06alipay\x12*\n" +
	"\x06wechat\x18\x02 \x01(\v2\x12.kratos.api.WechatR\x06wechat\x12;\n" +
	"\rcheck_pay_job\x18\x03 \x01(\v2\x17.kratos.api.CheckPayJobR\vcheckPayJob\x12M\n" +
	"\x15order_payment_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x13orderPaymentTimeout\x12M\n" +
	"\x15prepay_lease_duration\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x13prepayLeaseDuration\"\x8d\x02\n" +
	"\x06Alipay\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1f\n" +
	"\vprivate_key\x18\x02 \x01(\tR\n" +
	"privateKey\x12#\n" +
	"\ris_production\x18\x03 \x01(\bR\fisProduction\x12\"\n" +
	"\rapp_cert_path\x18\x04 \x01(\tR\vappCertPath\x125\n" +
	"\x17alipay_public_cert_path\x18\x05 \x01(\tR\x14alipayPublicCertPath\x121\n" +
	"\x15alipay_root_cert_path\x18\x06 \x01(\tR\x12alipayRootCertPath\x12\x18\n" +
	"\aenabled\x18\a \x01(\bR\aenabled\"\x8e\x01\n" +
	"\x06Wechat\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x15\n" +
	"\x06mch_id\x18\x02 \x01(\tR\x05mchId\x12\x17\n" +
	"\aapi_key\x18\x03 \x01(\tR\x06apiKey\x12#\n" +
	"\ris_production\x18\x04 \x01(\bR\fisProduction\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\"\xaa\x01\n" +
	"\vCheckPayJob\x12>\n" +
	"\rinitial_delay\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\finitialDelay\x12\x1b\n" +
	"\tmax_polls\x18\x02 \x01(\x05R\bmaxPolls\x12>\n" +
	"\rpoll_interval\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\fpollIntervalBEZCgithub.com/Dailiduzhou/simple-ecommerce/app/mall/internal/conf;confb\x06proto3"

var (
	file_conf_conf_proto_rawDescOnce sync.Once
	file_conf_conf_proto_rawDescData []byte
)

func file_conf_conf_proto_rawDescGZIP() []byte {
	file_conf_conf_proto_rawDescOnce.Do(func() {
		file_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)))
	})
	return file_conf_conf_proto_rawDescData
}

var file_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_conf_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),           // 0: kratos.api.Bootstrap
	(*Snowflake)(nil),           // 1: kratos.api.Snowflake
	(*Auth)(nil),                // 2: kratos.api.Auth
	(*Server)(nil),              // 3: kratos.api.Server
	(*Data)(nil),                // 4: kratos.api.Data
	(*Payment)(nil),             // 5: kratos.api.Payment
	(*Alipay)(nil),              // 6: kratos.api.Alipay
	(*Wechat)(nil),              // 7: kratos.api.Wechat
	(*CheckPayJob)(nil),         // 8: kratos.api.CheckPayJob
	(*Server_HTTP)(nil),         // 9: kratos.api.Server.HTTP
	(*Server_GRPC)(nil),         // 10: kratos.api.Server.GRPC
	(*Data_Database)(nil),       // 11: kratos.api.Data.Database
	(*Data_Redis)(nil),          // 12: kratos.api.Data.Redis
	(*durationpb.Duration)(nil), // 13: google.protobuf.Duration
}
var file_conf_conf_proto_depIdxs = []int32{
	3,  // 0: kratos.api.Bootstrap.server:type_name -> kratos.api.Server
	4,  // 1: kratos.api.Bootstrap.data:type_name -> kratos.api.Data
	2,  // 2: kratos.api.Bootstrap.auth:type_name -> kratos.api.Auth
	1,  // 3: kratos.api.Bootstrap.snowflake:type_name -> kratos.api.Snowflake
	5,  // 4: kratos.api.Bootstrap.payment:type_name -> kratos.api.Payment
	13, // 5: kratos.api.Auth.access_token_timeout:type_name -> google.protobuf.Duration
	13, // 6: kratos.api.Auth.refresh_token_timeout:type_name -> google.protobuf.Duration
	9,  // 7: kratos.api.Server.http:type_name -> kratos.api.Server.HTTP
	10, // 8: kratos.api.Server.grpc:type_name -> kratos.api.Server.GRPC
	11, // 9: kratos.api.Data.database:type_name -> kratos.api.Data.Database
	12, // 10: kratos.api.Data.redis:type_name -> kratos.api.Data.Redis
	6,  // 11: kratos.api.Payment.alipay:type_name -> kratos.api.Alipay
	7,  // 12: kratos.api.Payment.wechat:type_name -> kratos.api.Wechat
	8,  // 13: kratos.api.Payment.check_pay_job:type_name -> kratos.api.CheckPayJob
	13, // 14: kratos.api.Payment.order_payment_timeout:type_name -> google.protobuf.Duration
	13, // 15: kratos.api.Payment.prepay_lease_duration:type_name -> google.protobuf.Duration
	13, // 16: kratos.api.CheckPayJob.initial_delay:type_name -> google.protobuf.Duration
	13, // 17: kratos.api.CheckPayJob.poll_interval:type_name -> google.protobuf.Duration
	13, // 18: kratos.api.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	13, // 19: kratos.api.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	13, // 20: kratos.api.Data.Redis.read_timeout:type_name -> google.protobuf.Duration
	13, // 21: kratos.api.Data.Redis.write_timeout:type_name -> google.protobuf.Duration
	13, // 22: kratos.api.Data.Redis.dial_timeout:type_name -> google.protobuf.Duration
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_conf_conf_proto_init() }
func file_conf_conf_proto_init() {
	if File_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_conf_proto_goTypes,
		DependencyIndexes: file_conf_conf_proto_depIdxs,
		MessageInfos:      file_conf_conf_proto_msgTypes,
	}.Build()
	File_conf_conf_proto = out.File
	file_conf_conf_proto_goTypes = nil
	file_conf_conf_proto_depIdxs = nil
}
