package biz

import (
	"context"
	"testing"
	"time"
	"unicode/utf8"

	"github.com/stretchr/testify/require"
)

func wellnessAt(t *testing.T, instant string) *TodayWellness {
	t.Helper()
	now, err := time.Parse(time.RFC3339Nano, instant)
	require.NoError(t, err)
	uc := &wellnessUsecase{now: func() time.Time { return now }}
	card, err := uc.GetTodayWellness(context.Background())
	require.NoError(t, err)
	return card
}

func TestWellnessDateAndTermBoundaries(t *testing.T) {
	for _, tt := range []struct {
		name, instant, date, term string
	}{
		{"before_beijing_midnight", "2026-04-04T15:59:59.999999999Z", "2026-04-04", "春分"},
		{"at_beijing_midnight", "2026-04-04T16:00:00Z", "2026-04-05", "清明"},
		{"before_astronomical_transition", "2026-04-05T00:00:01+08:00", "2026-04-05", "清明"},
		{"ordinary_day", "2026-04-08T12:00:00+08:00", "2026-04-08", "清明"},
		{"same_instant_other_zone", "2026-04-04T09:00:00-07:00", "2026-04-05", "清明"},
		{"year_end", "2025-12-31T23:59:59+08:00", "2025-12-31", "冬至"},
		{"new_year", "2025-12-31T16:00:00Z", "2026-01-01", "冬至"},
		{"before_first_term", "2026-01-04T23:59:59+08:00", "2026-01-04", "冬至"},
		{"first_term", "2026-01-05T00:00:00+08:00", "2026-01-05", "小寒"},
		{"leap_day", "2024-02-29T12:00:00+08:00", "2024-02-29", "雨水"},
		{"different_year_qingming", "2024-04-04T00:00:00+08:00", "2024-04-04", "清明"},
		{"different_year_lichun", "2025-02-03T00:00:00+08:00", "2025-02-03", "立春"},
		{"lichun_not_fixed_date", "2026-02-03T12:00:00+08:00", "2026-02-03", "大寒"},
	} {
		t.Run(tt.name, func(t *testing.T) {
			card := wellnessAt(t, tt.instant)
			require.Equal(t, tt.date, card.Date)
			require.Equal(t, tt.term, card.SolarTerm)
			require.Equal(t, wellnessAdvice[tt.term], card.Advice)
		})
	}
}

// Fixed 2026 civil dates exercise every transition, including terms that fall
// close to midnight. These fixtures must not be generated by the code under test.
func TestWellnessAllSolarTerms2026(t *testing.T) {
	terms := []struct{ date, name string }{
		{"2026-01-05", "小寒"}, {"2026-01-20", "大寒"},
		{"2026-02-04", "立春"}, {"2026-02-18", "雨水"},
		{"2026-03-05", "惊蛰"}, {"2026-03-20", "春分"},
		{"2026-04-05", "清明"}, {"2026-04-20", "谷雨"},
		{"2026-05-05", "立夏"}, {"2026-05-21", "小满"},
		{"2026-06-05", "芒种"}, {"2026-06-21", "夏至"},
		{"2026-07-07", "小暑"}, {"2026-07-23", "大暑"},
		{"2026-08-07", "立秋"}, {"2026-08-23", "处暑"},
		{"2026-09-07", "白露"}, {"2026-09-23", "秋分"},
		{"2026-10-08", "寒露"}, {"2026-10-23", "霜降"},
		{"2026-11-07", "立冬"}, {"2026-11-22", "小雪"},
		{"2026-12-07", "大雪"}, {"2026-12-22", "冬至"},
	}
	require.Len(t, wellnessAdvice, 24)
	for i, term := range terms {
		t.Run(term.name, func(t *testing.T) {
			midnight, err := time.Parse(time.RFC3339, term.date+"T00:00:00+08:00")
			require.NoError(t, err)
			previous := terms[(i+23)%24].name
			before := wellnessAt(t, midnight.Add(-time.Nanosecond).Format(time.RFC3339Nano))
			require.Equal(t, previous, before.SolarTerm)
			at := wellnessAt(t, midnight.Format(time.RFC3339))
			require.Equal(t, term.name, at.SolarTerm)
			require.Equal(t, term.date, at.Date)
			require.Equal(t, wellnessAdvice[term.name], at.Advice)
			require.GreaterOrEqual(t, utf8.RuneCountInString(at.Advice), 20)
			require.LessOrEqual(t, utf8.RuneCountInString(at.Advice), 40)
			later := wellnessAt(t, midnight.Add(23*time.Hour).Format(time.RFC3339))
			require.Equal(t, at, later)
		})
	}
}

func TestWellnessAdviceIsStableWithinTerm(t *testing.T) {
	first := wellnessAt(t, "2026-04-05T00:00:00+08:00")
	last := wellnessAt(t, "2026-04-19T23:59:59+08:00")
	require.Equal(t, first.SolarTerm, last.SolarTerm)
	require.Equal(t, first.Advice, last.Advice)
	require.NotEqual(t, first.Date, last.Date)
}

func TestWellnessReadsClockOncePerRequest(t *testing.T) {
	calls := 0
	uc := &wellnessUsecase{now: func() time.Time {
		calls++
		return time.Date(2026, 4, 4, 23, 59, 59, 0, wellnessLocation).Add(time.Duration(calls-1) * time.Second)
	}}
	before, err := uc.GetTodayWellness(context.Background())
	require.NoError(t, err)
	require.Equal(t, 1, calls)
	require.Equal(t, "2026-04-04", before.Date)
	require.Equal(t, "春分", before.SolarTerm)
	after, err := uc.GetTodayWellness(context.Background())
	require.NoError(t, err)
	require.Equal(t, 2, calls)
	require.Equal(t, "2026-04-05", after.Date)
	require.Equal(t, "清明", after.SolarTerm)
}

func TestWellnessCanceledContext(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	card, err := NewWellnessUsecase().GetTodayWellness(ctx)
	require.ErrorIs(t, err, context.Canceled)
	require.Nil(t, card)
}

func TestWellnessConcurrentRequests(t *testing.T) {
	uc := &wellnessUsecase{now: func() time.Time {
		return time.Date(2026, 4, 8, 12, 0, 0, 0, wellnessLocation)
	}}
	for range 16 {
		t.Run("request", func(t *testing.T) {
			t.Parallel()
			card, err := uc.GetTodayWellness(context.Background())
			require.NoError(t, err)
			require.Equal(t, "2026-04-08", card.Date)
			require.Equal(t, "清明", card.SolarTerm)
			require.Equal(t, wellnessAdvice["清明"], card.Advice)
		})
	}
}
