// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: community/v1/community_error.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_POST_NOT_FOUND        ErrorReason = 0
	ErrorReason_COMMENT_NOT_FOUND     ErrorReason = 1
	ErrorReason_INVALID_REPLY_TARGET  ErrorReason = 2
	ErrorReason_COMMENT_THREAD_CLOSED ErrorReason = 3
	ErrorReason_POST_VERSION_CONFLICT ErrorReason = 4
	ErrorReason_INVALID_CONTENT       ErrorReason = 5
	ErrorReason_FORBIDDEN             ErrorReason = 6
	ErrorReason_INVALID_CURSOR        ErrorReason = 7
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "POST_NOT_FOUND",
		1: "COMMENT_NOT_FOUND",
		2: "INVALID_REPLY_TARGET",
		3: "COMMENT_THREAD_CLOSED",
		4: "POST_VERSION_CONFLICT",
		5: "INVALID_CONTENT",
		6: "FORBIDDEN",
		7: "INVALID_CURSOR",
	}
	ErrorReason_value = map[string]int32{
		"POST_NOT_FOUND":        0,
		"COMMENT_NOT_FOUND":     1,
		"INVALID_REPLY_TARGET":  2,
		"COMMENT_THREAD_CLOSED": 3,
		"POST_VERSION_CONFLICT": 4,
		"INVALID_CONTENT":       5,
		"FORBIDDEN":             6,
		"INVALID_CURSOR":        7,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_community_v1_community_error_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_community_v1_community_error_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_community_v1_community_error_proto_rawDescGZIP(), []int{0}
}

var File_community_v1_community_error_proto protoreflect.FileDescriptor

const file_community_v1_community_error_proto_rawDesc = "" +
	"\n" +
	"\"community/v1/community_error.proto\x12\x10api.community.v1\x1a\x13errors/errors.proto*\xf6\x01\n" +
	"\vErrorReason\x12\x18\n" +
	"\x0ePOST_NOT_FOUND\x10\x00\x1a\x04\xa8E\x94\x03\x12\x1b\n" +
	"\x11COMMENT_NOT_FOUND\x10\x01\x1a\x04\xa8E\x94\x03\x12\x1e\n" +
	"\x14INVALID_REPLY_TARGET\x10\x02\x1a\x04\xa8E\x90\x03\x12\x1f\n" +
	"\x15COMMENT_THREAD_CLOSED\x10\x03\x1a\x04\xa8E\x99\x03\x12\x1f\n" +
	"\x15POST_VERSION_CONFLICT\x10\x04\x1a\x04\xa8E\x99\x03\x12\x19\n" +
	"\x0fINVALID_CONTENT\x10\x05\x1a\x04\xa8E\x90\x03\x12\x13\n" +
	"\tFORBIDDEN\x10\x06\x1a\x04\xa8E\x93\x03\x12\x18\n" +
	"\x0eINVALID_CURSOR\x10\a\x1a\x04\xa8E\x90\x03\x1a\x04\xa0E\xf4\x03B=Z;github.com/Dailiduzhou/simple-ecommerce/api/community/v1;v1b\x06proto3"

var (
	file_community_v1_community_error_proto_rawDescOnce sync.Once
	file_community_v1_community_error_proto_rawDescData []byte
)

func file_community_v1_community_error_proto_rawDescGZIP() []byte {
	file_community_v1_community_error_proto_rawDescOnce.Do(func() {
		file_community_v1_community_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_community_v1_community_error_proto_rawDesc), len(file_community_v1_community_error_proto_rawDesc)))
	})
	return file_community_v1_community_error_proto_rawDescData
}

var file_community_v1_community_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_community_v1_community_error_proto_goTypes = []any{
	(ErrorReason)(0), // 0: api.community.v1.ErrorReason
}
var file_community_v1_community_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_community_v1_community_error_proto_init() }
func file_community_v1_community_error_proto_init() {
	if File_community_v1_community_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_community_v1_community_error_proto_rawDesc), len(file_community_v1_community_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_community_v1_community_error_proto_goTypes,
		DependencyIndexes: file_community_v1_community_error_proto_depIdxs,
		EnumInfos:         file_community_v1_community_error_proto_enumTypes,
	}.Build()
	File_community_v1_community_error_proto = out.File
	file_community_v1_community_error_proto_goTypes = nil
	file_community_v1_community_error_proto_depIdxs = nil
}
