DROP TABLE IF EXISTS post_comments;
DROP FUNCTION IF EXISTS check_post_comment_relationship();
DROP TABLE IF EXISTS post_likes;
DROP TABLE IF EXISTS post_images;
DROP TABLE IF EXISTS media_assets;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS product_browsing_history;
DROP TABLE IF EXISTS payment_reconciliation_failures;
DROP TABLE IF EXISTS payment_notifications;
DROP TABLE IF EXISTS order_refunds;
ALTER TABLE IF EXISTS orders DROP CONSTRAINT IF EXISTS fk_order_paid_payment;
DROP TABLE IF EXISTS payment_reconciliation_actions;
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS order_fulfillment_actions;
DROP TABLE IF EXISTS orders;
DROP FUNCTION IF EXISTS protect_order_shipping_snapshot();
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS stock_adjustments;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS shipping_addresses;
DROP TABLE IF EXISTS users;
DROP FUNCTION IF EXISTS enqueue_projection_invalidation();
DROP TABLE IF EXISTS cache_invalidations;

DROP EXTENSION IF EXISTS pg_trgm;
