// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Dailiduzhou/simple-ecommerce/app/mall/internal/biz"
	"github.com/Dailiduzhou/simple-ecommerce/app/mall/internal/conf"
	"github.com/Dailiduzhou/simple-ecommerce/app/mall/internal/data"
	"github.com/Dailiduzhou/simple-ecommerce/app/mall/internal/job"
	"github.com/Dailiduzhou/simple-ecommerce/app/mall/internal/server"
	"github.com/Dailiduzhou/simple-ecommerce/app/mall/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, snowflake *conf.Snowflake, payment *conf.Payment, community *conf.Community, storage *conf.Storage, logger log.Logger) (*kratos.App, func(), error) {
	pool, cleanup, err := data.NewPgxPool(confData)
	if err != nil {
		return nil, nil, err
	}
	client, err := data.NewRedisClient(confData)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	dataData, cleanup2, err := data.NewData(confData, pool, client)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	txManager := data.NewTransaction(pool, logger)
	riverInsertClient, err := data.NewRiverInsertClient(pool)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	communityPolicy, err := data.NewCommunityPolicy(community)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	mediaRepo := data.NewMediaRepo(dataData, txManager, riverInsertClient, communityPolicy)
	communityUserRepo := data.NewCommunityUserRepo(dataData, txManager, mediaRepo, logger)
	authRepo := data.NewAuthRepo(client, logger)
	authUsecase := biz.NewAuthUsecase(communityUserRepo, authRepo, auth)
	productRepo := data.NewProductRepo(dataData, logger)
	productUsecase := biz.NewProductUsecase(productRepo, logger)
	categoryRepo := data.NewCategoryRepo(dataData, logger)
	categoryUsecase := biz.NewCategoryUsecase(categoryRepo, logger)
	eventRepo := data.NewEventRepo(dataData, logger)
	eventUsecase := biz.NewEventUsecase(eventRepo, logger)
	wellnessUsecase := biz.NewWellnessUsecase()
	mallService := service.NewMallService(productUsecase, categoryUsecase, eventUsecase, wellnessUsecase, logger)
	userUsecase := biz.NewUserUsecase(communityUserRepo, authRepo, auth, logger)
	shippingAddressRepo := data.NewShippingAddressRepo(dataData, txManager, logger)
	shippingAddressUsecase := biz.NewShippingAddressUsecase(shippingAddressRepo, auth, logger)
	browsingHistoryRepo := data.NewBrowsingHistoryRepo(dataData, txManager, communityPolicy)
	browsingHistoryUsecase := biz.NewBrowsingHistoryUsecase(browsingHistoryRepo)
	userService := service.NewUserService(authUsecase, userUsecase, shippingAddressUsecase, browsingHistoryUsecase, logger)
	paymentMQRepo := data.NewPaymentMQRepoForWire(riverInsertClient, logger)
	orderRepo := data.NewOrderRepoWithJobs(dataData, txManager, paymentMQRepo, logger)
	snowflakeGenerator, err := data.NewSnowflakeIDGenerator(snowflake)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	orderPolicy := data.NewOrderPolicy(payment)
	orderUsecase := biz.NewConfiguredOrderUsecase(orderRepo, snowflakeGenerator, orderPolicy, logger)
	orderService := service.NewOrderService(orderUsecase)
	v, err := data.NewPaymentAdapters(payment, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	paymentGateway := biz.NewPaymentGateway(v)
	paymentRepo := data.NewPaymentRepoWithJobs(dataData, txManager, paymentMQRepo, logger)
	paymentNotificationRepo := data.NewPaymentNotificationRepo(txManager, paymentMQRepo)
	paymentJobUsecase := biz.NewPaymentJobUsecase(paymentMQRepo, logger)
	paymentPolicy := data.NewPaymentPolicy(payment)
	paymentUsecase := biz.NewConfiguredPaymentUsecase(paymentGateway, paymentRepo, paymentNotificationRepo, orderRepo, paymentJobUsecase, txManager, snowflakeGenerator, paymentPolicy, logger)
	paymentService := service.NewPaymentService(paymentUsecase, paymentJobUsecase, logger)
	postRepo := data.NewPostRepo(dataData, txManager, mediaRepo)
	objectStorage, err := data.NewObjectStorage(storage)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	mediaPolicy, err := data.NewMediaPolicy(storage)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	postUsecase := biz.NewPostUsecase(postRepo, objectStorage, mediaPolicy)
	commentRepo := data.NewCommentRepo(dataData, txManager)
	commentUsecase := biz.NewCommentUsecase(commentRepo)
	communityService := service.NewCommunityService(postUsecase, commentUsecase)
	mediaUsecase := biz.NewMediaUsecase(mediaRepo, objectStorage, mediaPolicy)
	mediaService := service.NewMediaService(mediaUsecase)
	writeLimiter, err := data.NewWriteLimiter(client, community, auth)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	grpcServer := server.NewGRPCServer(confServer, auth, authUsecase, mallService, userService, orderService, paymentService, communityService, mediaService, writeLimiter, logger)
	httpServer := server.NewHTTPServer(confServer, auth, authUsecase, mallService, userService, orderService, paymentService, communityService, mediaService, writeLimiter, logger)
	checkPayWorker := job.NewCheckPayWorker(paymentGateway, paymentRepo, logger)
	orderExpiryRepo := data.NewOrderExpiryRepo(dataData, txManager, paymentMQRepo, logger)
	expireOrderWorker := job.NewExpireOrderWorker(orderExpiryRepo)
	closePayWorker := job.NewClosePayWorker(paymentGateway, paymentRepo)
	reapExpiredOrdersWorker := job.NewReapExpiredOrdersWorker(orderExpiryRepo, logger)
	reconcileRefundsWorker := job.NewReconcileRefundsWorker(paymentUsecase, logger)
	browsingHistoryCleanupWorker := job.NewBrowsingHistoryCleanupWorker(browsingHistoryUsecase)
	mediaSweepWorker := job.NewMediaSweepWorker(mediaUsecase)
	mediaDeleteWorker := job.NewMediaDeleteWorker(mediaUsecase)
	workers := job.NewWorkers(checkPayWorker, expireOrderWorker, closePayWorker, reapExpiredOrdersWorker, reconcileRefundsWorker, browsingHistoryCleanupWorker, mediaSweepWorker, mediaDeleteWorker, logger)
	v2 := job.NewPeriodicJobs()
	paymentRiverErrorHandler := data.NewPaymentRiverErrorHandler(pool, client, logger)
	riverClient, err := data.NewConfiguredRiverClient(pool, workers, v2, paymentRiverErrorHandler, community)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	riverServer := job.NewRiverServer(riverClient)
	app := newApp(logger, grpcServer, httpServer, riverServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
