// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Dailiduzhou/simple-ecommerce/app/mall/internal/biz"
	"github.com/Dailiduzhou/simple-ecommerce/app/mall/internal/conf"
	"github.com/Dailiduzhou/simple-ecommerce/app/mall/internal/data"
	"github.com/Dailiduzhou/simple-ecommerce/app/mall/internal/server"
	"github.com/Dailiduzhou/simple-ecommerce/app/mall/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, logger log.Logger) (*kratos.App, func(), error) {
	pool, cleanup, err := data.NewPgxPool(confData)
	if err != nil {
		return nil, nil, err
	}
	client, err := data.NewRiverClient(pool)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	redisClient, err := data.NewRedisClient(confData)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	dataData, cleanup2, err := data.NewData(confData, pool, client, redisClient)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	authRepo := data.NewAuthRepo(redisClient, logger)
	authUsecase := biz.NewAuthUsecase(userRepo, authRepo, auth)
	mallService := service.NewMallService()
	userService := service.NewUserService(authUsecase, userRepo, logger)
	orderService := service.NewOrderService()
	paymentService := service.NewPaymentService()
	grpcServer := server.NewGRPCServer(confServer, auth, authUsecase, mallService, userService, orderService, paymentService, logger)
	httpServer := server.NewHTTPServer(confServer, auth, authUsecase, mallService, userService, orderService, paymentService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
