// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: browsing_history.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const cleanupBrowsingHistory = `-- name: CleanupBrowsingHistory :execrows
WITH expired AS (
  SELECT user_id, product_id
  FROM product_browsing_history
  -- 与列表页共用数据库时钟计算过期边界。
  WHERE last_viewed_at <= NOW() - make_interval(secs => $1::double precision)
  ORDER BY last_viewed_at, user_id, product_id
  LIMIT $2
  FOR UPDATE SKIP LOCKED
)
DELETE FROM product_browsing_history h
USING expired e
WHERE h.user_id = e.user_id
  AND h.product_id = e.product_id
  AND h.last_viewed_at <= NOW() - make_interval(secs => $1::double precision)
`

type CleanupBrowsingHistoryParams struct {
	RetentionSeconds float64
	BatchSize        int32
}

func (q *Queries) CleanupBrowsingHistory(ctx context.Context, arg CleanupBrowsingHistoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupBrowsingHistory, arg.RetentionSeconds, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearBrowsingHistory = `-- name: ClearBrowsingHistory :exec
DELETE FROM product_browsing_history
WHERE user_id = $1
`

func (q *Queries) ClearBrowsingHistory(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, clearBrowsingHistory, userID)
	return err
}

const deleteBrowsingHistoryItem = `-- name: DeleteBrowsingHistoryItem :exec
DELETE FROM product_browsing_history
WHERE user_id = $1
  AND product_id = $2
`

type DeleteBrowsingHistoryItemParams struct {
	UserID    int64
	ProductID int64
}

func (q *Queries) DeleteBrowsingHistoryItem(ctx context.Context, arg DeleteBrowsingHistoryItemParams) error {
	_, err := q.db.Exec(ctx, deleteBrowsingHistoryItem, arg.UserID, arg.ProductID)
	return err
}

const listBrowsingHistory = `-- name: ListBrowsingHistory :many
SELECT
  h.user_id, h.product_id, h.first_viewed_at, h.last_viewed_at,
  p.name,
  p.price_minor,
  p.discount,
  p.cover_image,
  (p.status = 1 AND p.deleted_at IS NULL)::boolean AS available
FROM product_browsing_history h
JOIN products p ON p.id = h.product_id
WHERE h.user_id = $1
  -- 过期判定使用数据库时钟，避免多实例应用时钟漂移导致边界不一致。
  AND h.last_viewed_at > NOW() - make_interval(secs => $2::double precision)
  AND (NOT $3::boolean OR h.last_viewed_at >= $4::timestamptz)
  AND (NOT $5::boolean OR h.last_viewed_at < $6::timestamptz)
  AND (
    NOT $7::boolean
    OR (h.last_viewed_at, h.product_id)
      < ($8::timestamptz, $9::bigint)
  )
ORDER BY h.last_viewed_at DESC, h.product_id DESC
LIMIT $10
`

type ListBrowsingHistoryParams struct {
	UserID           int64
	RetentionSeconds float64
	HasStart         bool
	StartTime        pgtype.Timestamptz
	HasEnd           bool
	EndTime          pgtype.Timestamptz
	HasCursor        bool
	CursorTime       pgtype.Timestamptz
	CursorID         int64
	PageLimit        int32
}

type ListBrowsingHistoryRow struct {
	UserID        int64
	ProductID     int64
	FirstViewedAt pgtype.Timestamptz
	LastViewedAt  pgtype.Timestamptz
	Name          string
	PriceMinor    int64
	Discount      decimal.Decimal
	CoverImage    []byte
	Available     bool
}

func (q *Queries) ListBrowsingHistory(ctx context.Context, arg ListBrowsingHistoryParams) ([]ListBrowsingHistoryRow, error) {
	rows, err := q.db.Query(ctx, listBrowsingHistory,
		arg.UserID,
		arg.RetentionSeconds,
		arg.HasStart,
		arg.StartTime,
		arg.HasEnd,
		arg.EndTime,
		arg.HasCursor,
		arg.CursorTime,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBrowsingHistoryRow
	for rows.Next() {
		var i ListBrowsingHistoryRow
		if err := rows.Scan(
			&i.UserID,
			&i.ProductID,
			&i.FirstViewedAt,
			&i.LastViewedAt,
			&i.Name,
			&i.PriceMinor,
			&i.Discount,
			&i.CoverImage,
			&i.Available,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCommunityUser = `-- name: LockCommunityUser :one
SELECT id, nickname, real_name, phone_hash, phone_encrypt, password_hash, password_changed_at, role, created_at, updated_at
FROM users
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockCommunityUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, lockCommunityUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.RealName,
		&i.PhoneHash,
		&i.PhoneEncrypt,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordProductView = `-- name: RecordProductView :one
INSERT INTO product_browsing_history (user_id, product_id, first_viewed_at, last_viewed_at)
SELECT
  $1,
  p.id,
  statement_timestamp(),
  statement_timestamp()
FROM products p
WHERE p.id = $2
  AND p.status = 1
  AND p.deleted_at IS NULL
ON CONFLICT (user_id, product_id) DO UPDATE
SET last_viewed_at = GREATEST(product_browsing_history.last_viewed_at, clock_timestamp())
RETURNING user_id, product_id, first_viewed_at, last_viewed_at
`

type RecordProductViewParams struct {
	UserID    int64
	ProductID int64
}

func (q *Queries) RecordProductView(ctx context.Context, arg RecordProductViewParams) (ProductBrowsingHistory, error) {
	row := q.db.QueryRow(ctx, recordProductView, arg.UserID, arg.ProductID)
	var i ProductBrowsingHistory
	err := row.Scan(
		&i.UserID,
		&i.ProductID,
		&i.FirstViewedAt,
		&i.LastViewedAt,
	)
	return i, err
}
