// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (parent_id, name, sort_order)
VALUES ($1, $2, $3)
RETURNING id, parent_id, name, created_at, updated_at, sort_order
`

type CreateCategoryParams struct {
	ParentID  pgtype.Int8
	Name      string
	SortOrder int32
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.ParentID, arg.Name, arg.SortOrder)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SortOrder,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, parent_id, name, created_at, updated_at, sort_order FROM categories WHERE id = $1
`

func (q *Queries) GetCategory(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SortOrder,
	)
	return i, err
}

const listSubCategories = `-- name: ListSubCategories :many
SELECT id, parent_id, name, created_at, updated_at, sort_order FROM categories WHERE parent_id = $1 ORDER BY sort_order, id
`

func (q *Queries) ListSubCategories(ctx context.Context, parentID pgtype.Int8) ([]Category, error) {
	rows, err := q.db.Query(ctx, listSubCategories, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopCategories = `-- name: ListTopCategories :many
SELECT id, parent_id, name, created_at, updated_at, sort_order FROM categories WHERE parent_id IS NULL ORDER BY sort_order, id
`

func (q *Queries) ListTopCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listTopCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = $2, sort_order = $3, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, parent_id, name, created_at, updated_at, sort_order
`

type UpdateCategoryParams struct {
	ID        int64
	Name      string
	SortOrder int32
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory, arg.ID, arg.Name, arg.SortOrder)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SortOrder,
	)
	return i, err
}
