// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type CacheInvalidation struct {
	ID             int64
	GenerationKeys []string
	CreatedAt      pgtype.Timestamptz
}

type Category struct {
	ID        int64
	ParentID  pgtype.Int8
	Name      string
	SortOrder int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Event struct {
	ID          int64
	Name        string
	Status      int16
	StartAt     pgtype.Timestamptz
	EndAt       pgtype.Timestamptz
	CoverImage  []byte
	MediaAssets []byte
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type MediaAsset struct {
	ID               int64
	OwnerID          pgtype.Int8
	Provider         string
	BucketName       string
	ObjectKey        string
	StagingKey       string
	StagingCleaned   bool
	StagingCleanupAt pgtype.Timestamptz
	ContentType      string
	SizeBytes        int64
	Width            int32
	Height           int32
	Status           string
	ExpiresAt        pgtype.Timestamptz
	UploadExpiresAt  pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type Order struct {
	ID                    int64
	UserID                int64
	AddressID             int64
	ReceiverName          string
	ReceiverPhoneEncrypt  string
	ShippingProvince      string
	ShippingCity          string
	ShippingDistrict      string
	ShippingDetailAddress string
	PaidPaymentID         pgtype.Int8
	TotalAmountMinor      int64
	Currency              string
	Status                string
	IsCompleted           bool
	OutTradeNo            string
	IdempotencyKey        string
	RequestHash           string
	ExpiresAt             pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type OrderFulfillmentAction struct {
	ID             int64
	OrderID        int64
	ActorID        int64
	Action         string
	FromStatus     string
	ToStatus       string
	IdempotencyKey string
	Reason         string
	Carrier        string
	TrackingNumber string
	CreatedAt      pgtype.Timestamptz
}

type OrderItem struct {
	ID                  int64
	OrderID             int64
	ProductID           int64
	Quantity            int32
	UnitPriceMinor      int64
	ProductNameSnapshot string
	CoverImageSnapshot  []byte
	CreatedAt           pgtype.Timestamptz
}

type OrderRefund struct {
	ID                int64
	OrderID           int64
	UserID            int64
	PaymentID         pgtype.Int8
	OutRefundNo       string
	TotalAmountMinor  int64
	RefundAmountMinor int64
	Currency          string
	Reason            string
	Purpose           string
	Status            string
	LastError         string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type Payment struct {
	ID                    int64
	OrderID               int64
	UserID                int64
	MerchantID            int64
	AmountMinor           int64
	Currency              string
	Status                string
	PayChannel            string
	ThirdPartyTxID        pgtype.Text
	OutTradeNo            string
	ActionType            pgtype.Text
	ActionPayload         []byte
	PaidAt                pgtype.Timestamptz
	ReconciliationStatus  string
	ReconciliationVersion int64
	ReconciliationReason  pgtype.Text
	ReconciliationDetail  pgtype.Text
	PrepayLeaseToken      pgtype.Text
	PrepayLeaseUntil      pgtype.Timestamptz
	PrepayAttempts        int32
	LastError             pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type PaymentNotification struct {
	ID              int64
	Provider        string
	ProviderEventID pgtype.Text
	OutTradeNo      string
	PayloadHash     string
	VerifiedAt      pgtype.Timestamptz
	ProcessedAt     pgtype.Timestamptz
	Status          string
	LastError       pgtype.Text
	RiverJobID      pgtype.Int8
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type PaymentReconciliationAction struct {
	ID             int64
	PaymentID      int64
	ActorID        int64
	Action         string
	FromStatus     string
	ToStatus       string
	FromVersion    int64
	ToVersion      int64
	IdempotencyKey string
	Reason         string
	Evidence       string
	RiverJobID     pgtype.Int8
	CreatedAt      pgtype.Timestamptz
}

type PaymentReconciliationFailure struct {
	ID         int64
	PaymentID  int64
	Provider   string
	Reason     string
	RiverJobID pgtype.Int8
	Attempt    int32
	LastError  string
	CreatedAt  pgtype.Timestamptz
	ResolvedAt pgtype.Timestamptz
}

type Post struct {
	ID        int64
	AuthorID  pgtype.Int8
	Title     string
	Content   string
	Version   int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type PostComment struct {
	ID               int64
	PostID           int64
	AuthorID         pgtype.Int8
	RootCommentID    pgtype.Int8
	ReplyToCommentID pgtype.Int8
	Content          string
	CreatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

type PostImage struct {
	PostID    int64
	MediaID   int64
	SortOrder int32
}

type PostLike struct {
	PostID    int64
	UserID    int64
	CreatedAt pgtype.Timestamptz
}

type Product struct {
	ID         int64
	CategoryID int64
	Name       string
	PriceMinor int64
	Discount   decimal.Decimal
	Stock      int32
	// 商品状态：0=下架，1=上架；当前业务未定义其他状态值
	Status      int16
	CoverImage  []byte
	MediaAssets []byte
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type ProductBrowsingHistory struct {
	UserID        int64
	ProductID     int64
	FirstViewedAt pgtype.Timestamptz
	LastViewedAt  pgtype.Timestamptz
}

type ShippingAddress struct {
	ID                   int64
	UserID               int64
	ReceiverName         string
	ReceiverPhoneHash    string
	ReceiverPhoneEncrypt string
	Province             string
	City                 string
	District             string
	DetailAddress        string
	AddressTag           pgtype.Text
	IsDefault            bool
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type StockAdjustment struct {
	ID             int64
	ProductID      int64
	ActorID        int64
	Delta          int32
	Reason         string
	IdempotencyKey string
	ResultingStock int32
	CreatedAt      pgtype.Timestamptz
}

// 电商系统用户表
type User struct {
	// 用户全局唯一ID
	ID       int64
	Nickname string
	RealName string
	// 手机号HMAC摘要，用于等值匹配登录
	PhoneHash string
	// 手机号AES对称加密密文，用于解密展示
	PhoneEncrypt string
	// Bcrypt加密后的密码
	PasswordHash string
	// 凭证版本；改密原子递增，令牌必须携带验证密码时读取的同一版本
	AuthVersion int64
	Role        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
