// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: post_comments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one
INSERT INTO post_comments (post_id, author_id, root_comment_id, reply_to_comment_id, content)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, post_id, author_id, root_comment_id, reply_to_comment_id, content, created_at, deleted_at
`

type CreateCommentParams struct {
	PostID           int64
	AuthorID         pgtype.Int8
	RootCommentID    pgtype.Int8
	ReplyToCommentID pgtype.Int8
	Content          string
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (PostComment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.PostID,
		arg.AuthorID,
		arg.RootCommentID,
		arg.ReplyToCommentID,
		arg.Content,
	)
	var i PostComment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.AuthorID,
		&i.RootCommentID,
		&i.ReplyToCommentID,
		&i.Content,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :execrows
UPDATE post_comments
SET content = '',
    deleted_at = clock_timestamp()
WHERE post_id = $1
  AND id = $2
  AND deleted_at IS NULL
  AND (author_id = $3 OR $4::boolean)
`

type DeleteCommentParams struct {
	PostID  int64
	ID      int64
	ActorID pgtype.Int8
	IsAdmin bool
}

func (q *Queries) DeleteComment(ctx context.Context, arg DeleteCommentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteComment,
		arg.PostID,
		arg.ID,
		arg.ActorID,
		arg.IsAdmin,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserComments = `-- name: DeleteUserComments :exec
UPDATE post_comments
SET content = '',
    deleted_at = clock_timestamp()
WHERE author_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) DeleteUserComments(ctx context.Context, authorID pgtype.Int8) error {
	_, err := q.db.Exec(ctx, deleteUserComments, authorID)
	return err
}

const getComment = `-- name: GetComment :one
SELECT id, post_id, author_id, root_comment_id, reply_to_comment_id, content, created_at, deleted_at
FROM post_comments
WHERE post_id = $1
  AND id = $2
`

type GetCommentParams struct {
	PostID int64
	ID     int64
}

func (q *Queries) GetComment(ctx context.Context, arg GetCommentParams) (PostComment, error) {
	row := q.db.QueryRow(ctx, getComment, arg.PostID, arg.ID)
	var i PostComment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.AuthorID,
		&i.RootCommentID,
		&i.ReplyToCommentID,
		&i.Content,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCommentReplies = `-- name: ListCommentReplies :many
SELECT
  c.id, c.post_id, c.author_id, c.root_comment_id, c.reply_to_comment_id, c.content, c.created_at, c.deleted_at,
  COALESCE(u.nickname, '已注销')::text AS nickname,
  (target.deleted_at IS NOT NULL)::boolean AS target_deleted,
  CASE
    WHEN target.deleted_at IS NULL THEN COALESCE(target.author_id, 0)
    ELSE 0
  END::bigint AS target_author_id,
  CASE
    WHEN target.deleted_at IS NULL THEN COALESCE(tu.nickname, '已注销')
    ELSE ''
  END::text AS target_nickname
FROM post_comments c
JOIN posts p ON p.id = c.post_id
LEFT JOIN users u ON u.id = c.author_id
JOIN post_comments target
  ON target.post_id = c.post_id
 AND target.id = c.reply_to_comment_id
LEFT JOIN users tu ON tu.id = target.author_id
WHERE c.post_id = $1
  AND p.deleted_at IS NULL
  AND c.root_comment_id = $2
  AND c.deleted_at IS NULL
  AND (
    NOT $3::boolean
    OR (c.created_at, c.id) > ($4::timestamptz, $5::bigint)
  )
ORDER BY c.created_at, c.id
LIMIT $6
`

type ListCommentRepliesParams struct {
	PostID     int64
	RootID     pgtype.Int8
	HasCursor  bool
	CursorTime pgtype.Timestamptz
	CursorID   int64
	PageLimit  int32
}

type ListCommentRepliesRow struct {
	ID               int64
	PostID           int64
	AuthorID         pgtype.Int8
	RootCommentID    pgtype.Int8
	ReplyToCommentID pgtype.Int8
	Content          string
	CreatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	Nickname         string
	TargetDeleted    bool
	TargetAuthorID   int64
	TargetNickname   string
}

func (q *Queries) ListCommentReplies(ctx context.Context, arg ListCommentRepliesParams) ([]ListCommentRepliesRow, error) {
	rows, err := q.db.Query(ctx, listCommentReplies,
		arg.PostID,
		arg.RootID,
		arg.HasCursor,
		arg.CursorTime,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentRepliesRow
	for rows.Next() {
		var i ListCommentRepliesRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.AuthorID,
			&i.RootCommentID,
			&i.ReplyToCommentID,
			&i.Content,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.Nickname,
			&i.TargetDeleted,
			&i.TargetAuthorID,
			&i.TargetNickname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootComments = `-- name: ListRootComments :many
SELECT
  c.id, c.post_id, c.author_id, c.root_comment_id, c.reply_to_comment_id, c.content, c.created_at, c.deleted_at,
  CASE WHEN c.deleted_at IS NULL THEN COALESCE(u.nickname, '已注销') ELSE '' END::text AS nickname,
  (
    SELECT count(*)
    FROM post_comments r
    WHERE r.post_id = c.post_id
      AND r.root_comment_id = c.id
      AND r.deleted_at IS NULL
  )::bigint AS reply_count
FROM post_comments c
LEFT JOIN users u ON u.id = c.author_id
JOIN posts p ON p.id = c.post_id
WHERE c.post_id = $1
  AND p.deleted_at IS NULL
  AND c.root_comment_id IS NULL
  AND (
    c.deleted_at IS NULL
    OR EXISTS (
      SELECT 1
      FROM post_comments r
      WHERE r.post_id = c.post_id
        AND r.root_comment_id = c.id
        AND r.deleted_at IS NULL
    )
  )
  AND (
    NOT $2::boolean
    OR (c.created_at, c.id) < ($3::timestamptz, $4::bigint)
  )
ORDER BY c.created_at DESC, c.id DESC
LIMIT $5
`

type ListRootCommentsParams struct {
	PostID     int64
	HasCursor  bool
	CursorTime pgtype.Timestamptz
	CursorID   int64
	PageLimit  int32
}

type ListRootCommentsRow struct {
	ID               int64
	PostID           int64
	AuthorID         pgtype.Int8
	RootCommentID    pgtype.Int8
	ReplyToCommentID pgtype.Int8
	Content          string
	CreatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	Nickname         string
	ReplyCount       int64
}

func (q *Queries) ListRootComments(ctx context.Context, arg ListRootCommentsParams) ([]ListRootCommentsRow, error) {
	rows, err := q.db.Query(ctx, listRootComments,
		arg.PostID,
		arg.HasCursor,
		arg.CursorTime,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRootCommentsRow
	for rows.Next() {
		var i ListRootCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.AuthorID,
			&i.RootCommentID,
			&i.ReplyToCommentID,
			&i.Content,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.Nickname,
			&i.ReplyCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
