// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (category_id, name, price, discount, stock, status, cover_image, media_assets, description)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, category_id, name, price, discount, stock, status, cover_image, media_assets, description, created_at, updated_at, deleted_at
`

type CreateProductParams struct {
	CategoryID  int64
	Name        string
	Price       decimal.Decimal
	Discount    decimal.Decimal
	Stock       int32
	Status      int16
	CoverImage  []byte
	MediaAssets []byte
	Description pgtype.Text
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.CategoryID,
		arg.Name,
		arg.Price,
		arg.Discount,
		arg.Stock,
		arg.Status,
		arg.CoverImage,
		arg.MediaAssets,
		arg.Description,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Price,
		&i.Discount,
		&i.Stock,
		&i.Status,
		&i.CoverImage,
		&i.MediaAssets,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const decrProductStock = `-- name: DecrProductStock :one
UPDATE products SET stock = stock - $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND stock >= $2 AND deleted_at IS NULL
RETURNING stock
`

type DecrProductStockParams struct {
	ID    int64
	Stock int32
}

func (q *Queries) DecrProductStock(ctx context.Context, arg DecrProductStockParams) (int32, error) {
	row := q.db.QueryRow(ctx, decrProductStock, arg.ID, arg.Stock)
	var stock int32
	err := row.Scan(&stock)
	return stock, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, category_id, name, price, discount, stock, status, cover_image, media_assets, description, created_at, updated_at, deleted_at FROM products WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProduct(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Price,
		&i.Discount,
		&i.Stock,
		&i.Status,
		&i.CoverImage,
		&i.MediaAssets,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, category_id, name, price, discount, stock, status, cover_image, media_assets, description, created_at, updated_at, deleted_at FROM products
WHERE deleted_at IS NULL
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Price,
			&i.Discount,
			&i.Stock,
			&i.Status,
			&i.CoverImage,
			&i.MediaAssets,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCategory = `-- name: ListProductsByCategory :many
SELECT id, category_id, name, price, discount, stock, status, cover_image, media_assets, description, created_at, updated_at, deleted_at FROM products
WHERE category_id = $1 AND status = 1 AND deleted_at IS NULL
ORDER BY id DESC
LIMIT $2 OFFSET $3
`

type ListProductsByCategoryParams struct {
	CategoryID int64
	Limit      int32
	Offset     int32
}

func (q *Queries) ListProductsByCategory(ctx context.Context, arg ListProductsByCategoryParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByCategory, arg.CategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Price,
			&i.Discount,
			&i.Stock,
			&i.Status,
			&i.CoverImage,
			&i.MediaAssets,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProduct = `-- name: SoftDeleteProduct :exec
UPDATE products SET deleted_at = CURRENT_TIMESTAMP WHERE id = $1
`

func (q *Queries) SoftDeleteProduct(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteProduct, id)
	return err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET category_id = $2, name = $3, price = $4, discount = $5, stock = $6,
    cover_image = $7, media_assets = $8, description = $9, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, category_id, name, price, discount, stock, status, cover_image, media_assets, description, created_at, updated_at, deleted_at
`

type UpdateProductParams struct {
	ID          int64
	CategoryID  int64
	Name        string
	Price       decimal.Decimal
	Discount    decimal.Decimal
	Stock       int32
	CoverImage  []byte
	MediaAssets []byte
	Description pgtype.Text
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.CategoryID,
		arg.Name,
		arg.Price,
		arg.Discount,
		arg.Stock,
		arg.CoverImage,
		arg.MediaAssets,
		arg.Description,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Price,
		&i.Discount,
		&i.Stock,
		&i.Status,
		&i.CoverImage,
		&i.MediaAssets,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateProductStatus = `-- name: UpdateProductStatus :exec
UPDATE products SET status = $2, updated_at = CURRENT_TIMESTAMP WHERE id = $1 AND deleted_at IS NULL
`

type UpdateProductStatusParams struct {
	ID     int64
	Status int16
}

func (q *Queries) UpdateProductStatus(ctx context.Context, arg UpdateProductStatusParams) error {
	_, err := q.db.Exec(ctx, updateProductStatus, arg.ID, arg.Status)
	return err
}
