// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reconciliation_actions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReconciliationAction = `-- name: CreateReconciliationAction :one
INSERT INTO payment_reconciliation_actions(payment_id,actor_id,action,from_status,to_status,from_version,to_version,idempotency_key,reason,evidence,river_job_id)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id, payment_id, actor_id, action, from_status, to_status, from_version, to_version, idempotency_key, reason, evidence, river_job_id, created_at
`

type CreateReconciliationActionParams struct {
	PaymentID      int64
	ActorID        int64
	Action         string
	FromStatus     string
	ToStatus       string
	FromVersion    int64
	ToVersion      int64
	IdempotencyKey string
	Reason         string
	Evidence       string
	RiverJobID     pgtype.Int8
}

func (q *Queries) CreateReconciliationAction(ctx context.Context, arg CreateReconciliationActionParams) (PaymentReconciliationAction, error) {
	row := q.db.QueryRow(ctx, createReconciliationAction,
		arg.PaymentID,
		arg.ActorID,
		arg.Action,
		arg.FromStatus,
		arg.ToStatus,
		arg.FromVersion,
		arg.ToVersion,
		arg.IdempotencyKey,
		arg.Reason,
		arg.Evidence,
		arg.RiverJobID,
	)
	var i PaymentReconciliationAction
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.ActorID,
		&i.Action,
		&i.FromStatus,
		&i.ToStatus,
		&i.FromVersion,
		&i.ToVersion,
		&i.IdempotencyKey,
		&i.Reason,
		&i.Evidence,
		&i.RiverJobID,
		&i.CreatedAt,
	)
	return i, err
}

const getReconciliationAction = `-- name: GetReconciliationAction :one
SELECT id, payment_id, actor_id, action, from_status, to_status, from_version, to_version, idempotency_key, reason, evidence, river_job_id, created_at FROM payment_reconciliation_actions WHERE payment_id=$1 AND idempotency_key=$2
`

type GetReconciliationActionParams struct {
	PaymentID      int64
	IdempotencyKey string
}

func (q *Queries) GetReconciliationAction(ctx context.Context, arg GetReconciliationActionParams) (PaymentReconciliationAction, error) {
	row := q.db.QueryRow(ctx, getReconciliationAction, arg.PaymentID, arg.IdempotencyKey)
	var i PaymentReconciliationAction
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.ActorID,
		&i.Action,
		&i.FromStatus,
		&i.ToStatus,
		&i.FromVersion,
		&i.ToVersion,
		&i.IdempotencyKey,
		&i.Reason,
		&i.Evidence,
		&i.RiverJobID,
		&i.CreatedAt,
	)
	return i, err
}

const hasUnresolvedProviderRefund = `-- name: HasUnresolvedProviderRefund :one
SELECT EXISTS (
  SELECT 1 FROM payment_reconciliation_failures
  WHERE payment_id=$1 AND reason='provider_side_refund' AND resolved_at IS NULL
)
`

func (q *Queries) HasUnresolvedProviderRefund(ctx context.Context, paymentID int64) (bool, error) {
	row := q.db.QueryRow(ctx, hasUnresolvedProviderRefund, paymentID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listReconciliationActions = `-- name: ListReconciliationActions :many
SELECT id, payment_id, actor_id, action, from_status, to_status, from_version, to_version, idempotency_key, reason, evidence, river_job_id, created_at FROM payment_reconciliation_actions WHERE payment_id=$1 AND id>$2 ORDER BY id LIMIT $3
`

type ListReconciliationActionsParams struct {
	PaymentID int64
	ID        int64
	Limit     int32
}

func (q *Queries) ListReconciliationActions(ctx context.Context, arg ListReconciliationActionsParams) ([]PaymentReconciliationAction, error) {
	rows, err := q.db.Query(ctx, listReconciliationActions, arg.PaymentID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentReconciliationAction
	for rows.Next() {
		var i PaymentReconciliationAction
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.ActorID,
			&i.Action,
			&i.FromStatus,
			&i.ToStatus,
			&i.FromVersion,
			&i.ToVersion,
			&i.IdempotencyKey,
			&i.Reason,
			&i.Evidence,
			&i.RiverJobID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReconciliationCases = `-- name: ListReconciliationCases :many
SELECT id, order_id, user_id, merchant_id, amount_minor, currency, status, pay_channel, third_party_tx_id, out_trade_no, action_type, action_payload, paid_at, reconciliation_status, reconciliation_version, reconciliation_reason, reconciliation_detail, prepay_lease_token, prepay_lease_until, prepay_attempts, last_error, created_at, updated_at FROM payments WHERE id > $1 AND reconciliation_status IN ('required','processing') ORDER BY id LIMIT $2
`

type ListReconciliationCasesParams struct {
	ID    int64
	Limit int32
}

func (q *Queries) ListReconciliationCases(ctx context.Context, arg ListReconciliationCasesParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listReconciliationCases, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.UserID,
			&i.MerchantID,
			&i.AmountMinor,
			&i.Currency,
			&i.Status,
			&i.PayChannel,
			&i.ThirdPartyTxID,
			&i.OutTradeNo,
			&i.ActionType,
			&i.ActionPayload,
			&i.PaidAt,
			&i.ReconciliationStatus,
			&i.ReconciliationVersion,
			&i.ReconciliationReason,
			&i.ReconciliationDetail,
			&i.PrepayLeaseToken,
			&i.PrepayLeaseUntil,
			&i.PrepayAttempts,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolvePaymentReconciliation = `-- name: ResolvePaymentReconciliation :one
WITH resolved AS (
  UPDATE payments SET reconciliation_status='resolved', reconciliation_version=payments.reconciliation_version+1, updated_at=clock_timestamp()
  WHERE payments.id=$1 AND payments.reconciliation_version=$2 AND payments.reconciliation_status IN ('required','processing') RETURNING payments.id, payments.order_id, payments.user_id, payments.merchant_id, payments.amount_minor, payments.currency, payments.status, payments.pay_channel, payments.third_party_tx_id, payments.out_trade_no, payments.action_type, payments.action_payload, payments.paid_at, payments.reconciliation_status, payments.reconciliation_version, payments.reconciliation_reason, payments.reconciliation_detail, payments.prepay_lease_token, payments.prepay_lease_until, payments.prepay_attempts, payments.last_error, payments.created_at, payments.updated_at
), cleared AS (
  UPDATE payment_reconciliation_failures f SET resolved_at=clock_timestamp()
  FROM resolved p WHERE f.payment_id=p.id AND f.resolved_at IS NULL
)
SELECT id, order_id, user_id, merchant_id, amount_minor, currency, status, pay_channel, third_party_tx_id, out_trade_no, action_type, action_payload, paid_at, reconciliation_status, reconciliation_version, reconciliation_reason, reconciliation_detail, prepay_lease_token, prepay_lease_until, prepay_attempts, last_error, created_at, updated_at FROM resolved
`

type ResolvePaymentReconciliationParams struct {
	ID                    int64
	ReconciliationVersion int64
}

type ResolvePaymentReconciliationRow struct {
	ID                    int64
	OrderID               int64
	UserID                int64
	MerchantID            int64
	AmountMinor           int64
	Currency              string
	Status                string
	PayChannel            string
	ThirdPartyTxID        pgtype.Text
	OutTradeNo            string
	ActionType            pgtype.Text
	ActionPayload         []byte
	PaidAt                pgtype.Timestamptz
	ReconciliationStatus  string
	ReconciliationVersion int64
	ReconciliationReason  pgtype.Text
	ReconciliationDetail  pgtype.Text
	PrepayLeaseToken      pgtype.Text
	PrepayLeaseUntil      pgtype.Timestamptz
	PrepayAttempts        int32
	LastError             pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

func (q *Queries) ResolvePaymentReconciliation(ctx context.Context, arg ResolvePaymentReconciliationParams) (ResolvePaymentReconciliationRow, error) {
	row := q.db.QueryRow(ctx, resolvePaymentReconciliation, arg.ID, arg.ReconciliationVersion)
	var i ResolvePaymentReconciliationRow
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.MerchantID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.PayChannel,
		&i.ThirdPartyTxID,
		&i.OutTradeNo,
		&i.ActionType,
		&i.ActionPayload,
		&i.PaidAt,
		&i.ReconciliationStatus,
		&i.ReconciliationVersion,
		&i.ReconciliationReason,
		&i.ReconciliationDetail,
		&i.PrepayLeaseToken,
		&i.PrepayLeaseUntil,
		&i.PrepayAttempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const retryPaymentReconciliation = `-- name: RetryPaymentReconciliation :one
UPDATE payments SET reconciliation_status='processing', reconciliation_version=reconciliation_version+1, updated_at=clock_timestamp()
WHERE id=$1 AND reconciliation_version=$2 AND reconciliation_status='required' RETURNING id, order_id, user_id, merchant_id, amount_minor, currency, status, pay_channel, third_party_tx_id, out_trade_no, action_type, action_payload, paid_at, reconciliation_status, reconciliation_version, reconciliation_reason, reconciliation_detail, prepay_lease_token, prepay_lease_until, prepay_attempts, last_error, created_at, updated_at
`

type RetryPaymentReconciliationParams struct {
	ID                    int64
	ReconciliationVersion int64
}

func (q *Queries) RetryPaymentReconciliation(ctx context.Context, arg RetryPaymentReconciliationParams) (Payment, error) {
	row := q.db.QueryRow(ctx, retryPaymentReconciliation, arg.ID, arg.ReconciliationVersion)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.MerchantID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.PayChannel,
		&i.ThirdPartyTxID,
		&i.OutTradeNo,
		&i.ActionType,
		&i.ActionPayload,
		&i.PaidAt,
		&i.ReconciliationStatus,
		&i.ReconciliationVersion,
		&i.ReconciliationReason,
		&i.ReconciliationDetail,
		&i.PrepayLeaseToken,
		&i.PrepayLeaseUntil,
		&i.PrepayAttempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
