// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shipping_addresses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearDefaultShippingAddress = `-- name: ClearDefaultShippingAddress :exec
UPDATE shipping_addresses SET is_default = FALSE, updated_at = CURRENT_TIMESTAMP WHERE user_id = $1
`

func (q *Queries) ClearDefaultShippingAddress(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, clearDefaultShippingAddress, userID)
	return err
}

const createShippingAddress = `-- name: CreateShippingAddress :one
INSERT INTO shipping_addresses (user_id, receiver_name, receiver_phone_hash, receiver_phone_encrypt, province, city, district, detail_address, address_tag, is_default)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, receiver_name, receiver_phone_hash, receiver_phone_encrypt, province, city, district, detail_address, address_tag, is_default, created_at, updated_at
`

type CreateShippingAddressParams struct {
	UserID               int64
	ReceiverName         string
	ReceiverPhoneHash    string
	ReceiverPhoneEncrypt string
	Province             string
	City                 string
	District             string
	DetailAddress        string
	AddressTag           pgtype.Text
	IsDefault            bool
}

func (q *Queries) CreateShippingAddress(ctx context.Context, arg CreateShippingAddressParams) (ShippingAddress, error) {
	row := q.db.QueryRow(ctx, createShippingAddress,
		arg.UserID,
		arg.ReceiverName,
		arg.ReceiverPhoneHash,
		arg.ReceiverPhoneEncrypt,
		arg.Province,
		arg.City,
		arg.District,
		arg.DetailAddress,
		arg.AddressTag,
		arg.IsDefault,
	)
	var i ShippingAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ReceiverName,
		&i.ReceiverPhoneHash,
		&i.ReceiverPhoneEncrypt,
		&i.Province,
		&i.City,
		&i.District,
		&i.DetailAddress,
		&i.AddressTag,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteShippingAddress = `-- name: DeleteShippingAddress :exec
DELETE FROM shipping_addresses WHERE id = $1 AND user_id = $2
`

type DeleteShippingAddressParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteShippingAddress(ctx context.Context, arg DeleteShippingAddressParams) error {
	_, err := q.db.Exec(ctx, deleteShippingAddress, arg.ID, arg.UserID)
	return err
}

const getDefaultShippingAddress = `-- name: GetDefaultShippingAddress :one
SELECT id, user_id, receiver_name, receiver_phone_hash, receiver_phone_encrypt, province, city, district, detail_address, address_tag, is_default, created_at, updated_at FROM shipping_addresses WHERE user_id = $1 AND is_default = TRUE LIMIT 1
`

func (q *Queries) GetDefaultShippingAddress(ctx context.Context, userID int64) (ShippingAddress, error) {
	row := q.db.QueryRow(ctx, getDefaultShippingAddress, userID)
	var i ShippingAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ReceiverName,
		&i.ReceiverPhoneHash,
		&i.ReceiverPhoneEncrypt,
		&i.Province,
		&i.City,
		&i.District,
		&i.DetailAddress,
		&i.AddressTag,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShippingAddress = `-- name: GetShippingAddress :one
SELECT id, user_id, receiver_name, receiver_phone_hash, receiver_phone_encrypt, province, city, district, detail_address, address_tag, is_default, created_at, updated_at FROM shipping_addresses WHERE id = $1 AND user_id = $2
`

type GetShippingAddressParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetShippingAddress(ctx context.Context, arg GetShippingAddressParams) (ShippingAddress, error) {
	row := q.db.QueryRow(ctx, getShippingAddress, arg.ID, arg.UserID)
	var i ShippingAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ReceiverName,
		&i.ReceiverPhoneHash,
		&i.ReceiverPhoneEncrypt,
		&i.Province,
		&i.City,
		&i.District,
		&i.DetailAddress,
		&i.AddressTag,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listShippingAddressesByUser = `-- name: ListShippingAddressesByUser :many
SELECT id, user_id, receiver_name, receiver_phone_hash, receiver_phone_encrypt, province, city, district, detail_address, address_tag, is_default, created_at, updated_at FROM shipping_addresses WHERE user_id = $1 ORDER BY is_default DESC, id DESC
`

func (q *Queries) ListShippingAddressesByUser(ctx context.Context, userID int64) ([]ShippingAddress, error) {
	rows, err := q.db.Query(ctx, listShippingAddressesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShippingAddress
	for rows.Next() {
		var i ShippingAddress
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ReceiverName,
			&i.ReceiverPhoneHash,
			&i.ReceiverPhoneEncrypt,
			&i.Province,
			&i.City,
			&i.District,
			&i.DetailAddress,
			&i.AddressTag,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultShippingAddress = `-- name: SetDefaultShippingAddress :exec
UPDATE shipping_addresses SET is_default = TRUE, updated_at = CURRENT_TIMESTAMP WHERE id = $1 AND user_id = $2
`

type SetDefaultShippingAddressParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) SetDefaultShippingAddress(ctx context.Context, arg SetDefaultShippingAddressParams) error {
	_, err := q.db.Exec(ctx, setDefaultShippingAddress, arg.ID, arg.UserID)
	return err
}

const updateShippingAddress = `-- name: UpdateShippingAddress :one
UPDATE shipping_addresses
SET receiver_name = $3, receiver_phone_hash = $4, receiver_phone_encrypt = $5,
    province = $6, city = $7, district = $8, detail_address = $9, address_tag = $10,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, receiver_name, receiver_phone_hash, receiver_phone_encrypt, province, city, district, detail_address, address_tag, is_default, created_at, updated_at
`

type UpdateShippingAddressParams struct {
	ID                   int64
	UserID               int64
	ReceiverName         string
	ReceiverPhoneHash    string
	ReceiverPhoneEncrypt string
	Province             string
	City                 string
	District             string
	DetailAddress        string
	AddressTag           pgtype.Text
}

func (q *Queries) UpdateShippingAddress(ctx context.Context, arg UpdateShippingAddressParams) (ShippingAddress, error) {
	row := q.db.QueryRow(ctx, updateShippingAddress,
		arg.ID,
		arg.UserID,
		arg.ReceiverName,
		arg.ReceiverPhoneHash,
		arg.ReceiverPhoneEncrypt,
		arg.Province,
		arg.City,
		arg.District,
		arg.DetailAddress,
		arg.AddressTag,
	)
	var i ShippingAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ReceiverName,
		&i.ReceiverPhoneHash,
		&i.ReceiverPhoneEncrypt,
		&i.Province,
		&i.City,
		&i.District,
		&i.DetailAddress,
		&i.AddressTag,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
