// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.35.1
// source: payment/v1/payment.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationPaymentClosePayment = "/api.payment.v1.Payment/ClosePayment"
const OperationPaymentCreatePayment = "/api.payment.v1.Payment/CreatePayment"
const OperationPaymentCreatePaymentCheckJob = "/api.payment.v1.Payment/CreatePaymentCheckJob"
const OperationPaymentGetMQJob = "/api.payment.v1.Payment/GetMQJob"
const OperationPaymentGetPayment = "/api.payment.v1.Payment/GetPayment"
const OperationPaymentGetPaymentByOrder = "/api.payment.v1.Payment/GetPaymentByOrder"
const OperationPaymentQueryPayment = "/api.payment.v1.Payment/QueryPayment"
const OperationPaymentRefundPayment = "/api.payment.v1.Payment/RefundPayment"

type PaymentHTTPServer interface {
	// ClosePayment 统一关闭订单(原 WechatPayService.CloseOrder + AliPayService.CloseOrder)。
	ClosePayment(context.Context, *ClosePaymentReq) (*ClosePaymentReply, error)
	// CreatePayment 统一创建支付:取订单 → 建支付流水 → 调三方 → 返回前端动作。
	// 同时取代了旧 Payment.CreatePayment(写流水) + WechatPayService.PrepayJSAPI
	// + AliPayService.Prepay 三个 RPC。
	CreatePayment(context.Context, *CreatePaymentReq) (*CreatePaymentReply, error)
	CreatePaymentCheckJob(context.Context, *CreatePaymentCheckJobRequest) (*MQJobInfo, error)
	GetMQJob(context.Context, *GetMQJobRequest) (*MQJobInfo, error)
	GetPayment(context.Context, *GetPaymentRequest) (*PaymentInfo, error)
	GetPaymentByOrder(context.Context, *GetPaymentByOrderRequest) (*PaymentInfo, error)
	// QueryPayment 统一查询订单(原 WechatPayService.QueryOrder + AliPayService.QueryOrder)。
	QueryPayment(context.Context, *QueryPaymentReq) (*QueryPaymentReply, error)
	// RefundPayment 管理员对指定支付发起整笔全额退款。
	RefundPayment(context.Context, *RefundPaymentRequest) (*RefundPaymentReply, error)
}

func RegisterPaymentHTTPServer(s *http.Server, srv PaymentHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/payments", _Payment_CreatePayment0_HTTP_Handler(srv))
	r.GET("/v1/payments/lookup", _Payment_QueryPayment0_HTTP_Handler(srv))
	r.POST("/v1/payments/lookup/close", _Payment_ClosePayment0_HTTP_Handler(srv))
	r.GET("/v1/payments/{id}", _Payment_GetPayment0_HTTP_Handler(srv))
	r.GET("/v1/orders/{order_id}/payment", _Payment_GetPaymentByOrder0_HTTP_Handler(srv))
	r.POST("/v1/payments/{id}/refund", _Payment_RefundPayment0_HTTP_Handler(srv))
	r.POST("/v1/payments/{payment_id}/checks", _Payment_CreatePaymentCheckJob0_HTTP_Handler(srv))
	r.GET("/v1/payments/mq/jobs/{job_id}", _Payment_GetMQJob0_HTTP_Handler(srv))
}

func _Payment_CreatePayment0_HTTP_Handler(srv PaymentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreatePaymentReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPaymentCreatePayment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreatePayment(ctx, req.(*CreatePaymentReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreatePaymentReply)
		return ctx.Result(200, reply)
	}
}

func _Payment_QueryPayment0_HTTP_Handler(srv PaymentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in QueryPaymentReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPaymentQueryPayment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.QueryPayment(ctx, req.(*QueryPaymentReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*QueryPaymentReply)
		return ctx.Result(200, reply)
	}
}

func _Payment_ClosePayment0_HTTP_Handler(srv PaymentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ClosePaymentReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPaymentClosePayment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ClosePayment(ctx, req.(*ClosePaymentReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ClosePaymentReply)
		return ctx.Result(200, reply)
	}
}

func _Payment_GetPayment0_HTTP_Handler(srv PaymentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPaymentRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPaymentGetPayment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPayment(ctx, req.(*GetPaymentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PaymentInfo)
		return ctx.Result(200, reply)
	}
}

func _Payment_GetPaymentByOrder0_HTTP_Handler(srv PaymentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPaymentByOrderRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPaymentGetPaymentByOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPaymentByOrder(ctx, req.(*GetPaymentByOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PaymentInfo)
		return ctx.Result(200, reply)
	}
}

func _Payment_RefundPayment0_HTTP_Handler(srv PaymentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RefundPaymentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPaymentRefundPayment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RefundPayment(ctx, req.(*RefundPaymentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RefundPaymentReply)
		return ctx.Result(200, reply)
	}
}

func _Payment_CreatePaymentCheckJob0_HTTP_Handler(srv PaymentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreatePaymentCheckJobRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPaymentCreatePaymentCheckJob)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreatePaymentCheckJob(ctx, req.(*CreatePaymentCheckJobRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MQJobInfo)
		return ctx.Result(200, reply)
	}
}

func _Payment_GetMQJob0_HTTP_Handler(srv PaymentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMQJobRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPaymentGetMQJob)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMQJob(ctx, req.(*GetMQJobRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MQJobInfo)
		return ctx.Result(200, reply)
	}
}

type PaymentHTTPClient interface {
	// ClosePayment 统一关闭订单(原 WechatPayService.CloseOrder + AliPayService.CloseOrder)。
	ClosePayment(ctx context.Context, req *ClosePaymentReq, opts ...http.CallOption) (rsp *ClosePaymentReply, err error)
	// CreatePayment 统一创建支付:取订单 → 建支付流水 → 调三方 → 返回前端动作。
	// 同时取代了旧 Payment.CreatePayment(写流水) + WechatPayService.PrepayJSAPI
	// + AliPayService.Prepay 三个 RPC。
	CreatePayment(ctx context.Context, req *CreatePaymentReq, opts ...http.CallOption) (rsp *CreatePaymentReply, err error)
	CreatePaymentCheckJob(ctx context.Context, req *CreatePaymentCheckJobRequest, opts ...http.CallOption) (rsp *MQJobInfo, err error)
	GetMQJob(ctx context.Context, req *GetMQJobRequest, opts ...http.CallOption) (rsp *MQJobInfo, err error)
	GetPayment(ctx context.Context, req *GetPaymentRequest, opts ...http.CallOption) (rsp *PaymentInfo, err error)
	GetPaymentByOrder(ctx context.Context, req *GetPaymentByOrderRequest, opts ...http.CallOption) (rsp *PaymentInfo, err error)
	// QueryPayment 统一查询订单(原 WechatPayService.QueryOrder + AliPayService.QueryOrder)。
	QueryPayment(ctx context.Context, req *QueryPaymentReq, opts ...http.CallOption) (rsp *QueryPaymentReply, err error)
	// RefundPayment 管理员对指定支付发起整笔全额退款。
	RefundPayment(ctx context.Context, req *RefundPaymentRequest, opts ...http.CallOption) (rsp *RefundPaymentReply, err error)
}

type PaymentHTTPClientImpl struct {
	cc *http.Client
}

func NewPaymentHTTPClient(client *http.Client) PaymentHTTPClient {
	return &PaymentHTTPClientImpl{client}
}

// ClosePayment 统一关闭订单(原 WechatPayService.CloseOrder + AliPayService.CloseOrder)。
func (c *PaymentHTTPClientImpl) ClosePayment(ctx context.Context, in *ClosePaymentReq, opts ...http.CallOption) (*ClosePaymentReply, error) {
	var out ClosePaymentReply
	pattern := "/v1/payments/lookup/close"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPaymentClosePayment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreatePayment 统一创建支付:取订单 → 建支付流水 → 调三方 → 返回前端动作。
// 同时取代了旧 Payment.CreatePayment(写流水) + WechatPayService.PrepayJSAPI
// + AliPayService.Prepay 三个 RPC。
func (c *PaymentHTTPClientImpl) CreatePayment(ctx context.Context, in *CreatePaymentReq, opts ...http.CallOption) (*CreatePaymentReply, error) {
	var out CreatePaymentReply
	pattern := "/v1/payments"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPaymentCreatePayment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PaymentHTTPClientImpl) CreatePaymentCheckJob(ctx context.Context, in *CreatePaymentCheckJobRequest, opts ...http.CallOption) (*MQJobInfo, error) {
	var out MQJobInfo
	pattern := "/v1/payments/{payment_id}/checks"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPaymentCreatePaymentCheckJob))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PaymentHTTPClientImpl) GetMQJob(ctx context.Context, in *GetMQJobRequest, opts ...http.CallOption) (*MQJobInfo, error) {
	var out MQJobInfo
	pattern := "/v1/payments/mq/jobs/{job_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPaymentGetMQJob))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PaymentHTTPClientImpl) GetPayment(ctx context.Context, in *GetPaymentRequest, opts ...http.CallOption) (*PaymentInfo, error) {
	var out PaymentInfo
	pattern := "/v1/payments/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPaymentGetPayment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PaymentHTTPClientImpl) GetPaymentByOrder(ctx context.Context, in *GetPaymentByOrderRequest, opts ...http.CallOption) (*PaymentInfo, error) {
	var out PaymentInfo
	pattern := "/v1/orders/{order_id}/payment"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPaymentGetPaymentByOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// QueryPayment 统一查询订单(原 WechatPayService.QueryOrder + AliPayService.QueryOrder)。
func (c *PaymentHTTPClientImpl) QueryPayment(ctx context.Context, in *QueryPaymentReq, opts ...http.CallOption) (*QueryPaymentReply, error) {
	var out QueryPaymentReply
	pattern := "/v1/payments/lookup"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPaymentQueryPayment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RefundPayment 管理员对指定支付发起整笔全额退款。
func (c *PaymentHTTPClientImpl) RefundPayment(ctx context.Context, in *RefundPaymentRequest, opts ...http.CallOption) (*RefundPaymentReply, error) {
	var out RefundPaymentReply
	pattern := "/v1/payments/{id}/refund"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPaymentRefundPayment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
