// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: payment/v1/payment.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TradeState int32

const (
	TradeState_TRADE_STATE_UNSPECIFIED TradeState = 0
	TradeState_SUCCESS                 TradeState = 1 // 支付成功
	TradeState_REFUND                  TradeState = 2 // 转入退款
	TradeState_NOTPAY                  TradeState = 3 // 未支付
	TradeState_CLOSED                  TradeState = 4 // 已关闭
	TradeState_REVOKED                 TradeState = 5 // 已撤销
	TradeState_USERPAYING              TradeState = 6 // 用户支付中
	TradeState_PAYERROR                TradeState = 7 // 支付失败
)

// Enum value maps for TradeState.
var (
	TradeState_name = map[int32]string{
		0: "TRADE_STATE_UNSPECIFIED",
		1: "SUCCESS",
		2: "REFUND",
		3: "NOTPAY",
		4: "CLOSED",
		5: "REVOKED",
		6: "USERPAYING",
		7: "PAYERROR",
	}
	TradeState_value = map[string]int32{
		"TRADE_STATE_UNSPECIFIED": 0,
		"SUCCESS":                 1,
		"REFUND":                  2,
		"NOTPAY":                  3,
		"CLOSED":                  4,
		"REVOKED":                 5,
		"USERPAYING":              6,
		"PAYERROR":                7,
	}
)

func (x TradeState) Enum() *TradeState {
	p := new(TradeState)
	*p = x
	return p
}

func (x TradeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TradeState) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_v1_payment_proto_enumTypes[0].Descriptor()
}

func (TradeState) Type() protoreflect.EnumType {
	return &file_payment_v1_payment_proto_enumTypes[0]
}

func (x TradeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TradeState.Descriptor instead.
func (TradeState) EnumDescriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

// 统一创建支付请求。
// - order_no: 商户订单号(对应 orders.out_trade_no)。
// - method: provider-neutral 的 "provider:product"，例如 "alipay:wap"。
// - client_ip: 客户端 IP,微信风控必传。
// - extra_params: 渠道特有的扩展参数抹平字段:
//   - WECHAT_JSAPI 必须传 "openid"。
//   - ALIPAY_WAP 可传 "return_url"。
//
// - description: 可选;省略时服务端从订单号生成安全描述。
// - total_amount: 已废弃且服务端忽略，金额只从订单读取。
type CreatePaymentReq struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	OrderNo     string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	Method      string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	ClientIp    string                 `protobuf:"bytes,3,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	ExtraParams map[string]string      `protobuf:"bytes,4,rep,name=extra_params,json=extraParams,proto3" json:"extra_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Description string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// Deprecated: Marked as deprecated in payment/v1/payment.proto.
	TotalAmount   int32 `protobuf:"varint,6,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentReq) Reset() {
	*x = CreatePaymentReq{}
	mi := &file_payment_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentReq) ProtoMessage() {}

func (x *CreatePaymentReq) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentReq.ProtoReflect.Descriptor instead.
func (*CreatePaymentReq) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePaymentReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *CreatePaymentReq) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CreatePaymentReq) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *CreatePaymentReq) GetExtraParams() map[string]string {
	if x != nil {
		return x.ExtraParams
	}
	return nil
}

func (x *CreatePaymentReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Deprecated: Marked as deprecated in payment/v1/payment.proto.
func (x *CreatePaymentReq) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

// 统一创建支付响应。
// - action_type: 告诉前端该怎么处理 payload。
//   - "form"     — 提交表单。
//   - "redirect" — 跳转链接。
//   - "invoke"   — 调用客户端支付 SDK/API。
//
// - payload: 渠道真实的支付参数,序列化为 JSON 字符串,字段契约见 service 注释。
type CreatePaymentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionType    string                 `protobuf:"bytes,1,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentReply) Reset() {
	*x = CreatePaymentReply{}
	mi := &file_payment_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentReply) ProtoMessage() {}

func (x *CreatePaymentReply) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentReply.ProtoReflect.Descriptor instead.
func (*CreatePaymentReply) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentReply) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *CreatePaymentReply) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type QueryPaymentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutTradeNo    string                 `protobuf:"bytes,1,opt,name=out_trade_no,json=outTradeNo,proto3" json:"out_trade_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPaymentReq) Reset() {
	*x = QueryPaymentReq{}
	mi := &file_payment_v1_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPaymentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPaymentReq) ProtoMessage() {}

func (x *QueryPaymentReq) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPaymentReq.ProtoReflect.Descriptor instead.
func (*QueryPaymentReq) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{2}
}

func (x *QueryPaymentReq) GetOutTradeNo() string {
	if x != nil {
		return x.OutTradeNo
	}
	return ""
}

type QueryPaymentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutTradeNo    string                 `protobuf:"bytes,1,opt,name=out_trade_no,json=outTradeNo,proto3" json:"out_trade_no,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	TradeState    TradeState             `protobuf:"varint,3,opt,name=trade_state,json=tradeState,proto3,enum=api.payment.v1.TradeState" json:"trade_state,omitempty"`
	AmountMinor   int64                  `protobuf:"varint,4,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPaymentReply) Reset() {
	*x = QueryPaymentReply{}
	mi := &file_payment_v1_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPaymentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPaymentReply) ProtoMessage() {}

func (x *QueryPaymentReply) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPaymentReply.ProtoReflect.Descriptor instead.
func (*QueryPaymentReply) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{3}
}

func (x *QueryPaymentReply) GetOutTradeNo() string {
	if x != nil {
		return x.OutTradeNo
	}
	return ""
}

func (x *QueryPaymentReply) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *QueryPaymentReply) GetTradeState() TradeState {
	if x != nil {
		return x.TradeState
	}
	return TradeState_TRADE_STATE_UNSPECIFIED
}

func (x *QueryPaymentReply) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

func (x *QueryPaymentReply) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type ClosePaymentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutTradeNo    string                 `protobuf:"bytes,1,opt,name=out_trade_no,json=outTradeNo,proto3" json:"out_trade_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClosePaymentReq) Reset() {
	*x = ClosePaymentReq{}
	mi := &file_payment_v1_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClosePaymentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClosePaymentReq) ProtoMessage() {}

func (x *ClosePaymentReq) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClosePaymentReq.ProtoReflect.Descriptor instead.
func (*ClosePaymentReq) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{4}
}

func (x *ClosePaymentReq) GetOutTradeNo() string {
	if x != nil {
		return x.OutTradeNo
	}
	return ""
}

type ClosePaymentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClosePaymentReply) Reset() {
	*x = ClosePaymentReply{}
	mi := &file_payment_v1_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClosePaymentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClosePaymentReply) ProtoMessage() {}

func (x *ClosePaymentReply) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClosePaymentReply.ProtoReflect.Descriptor instead.
func (*ClosePaymentReply) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{5}
}

func (x *ClosePaymentReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PaymentInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId        int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId         int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MerchantId     int64                  `protobuf:"varint,4,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	AmountMinor    int64                  `protobuf:"varint,5,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Method         string                 `protobuf:"bytes,7,opt,name=method,proto3" json:"method,omitempty"`
	ThirdPartyTxId string                 `protobuf:"bytes,8,opt,name=third_party_tx_id,json=thirdPartyTxId,proto3" json:"third_party_tx_id,omitempty"`
	PaidAt         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	OutTradeNo     string                 `protobuf:"bytes,11,opt,name=out_trade_no,json=outTradeNo,proto3" json:"out_trade_no,omitempty"`
	Currency       string                 `protobuf:"bytes,12,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PaymentInfo) Reset() {
	*x = PaymentInfo{}
	mi := &file_payment_v1_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentInfo) ProtoMessage() {}

func (x *PaymentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentInfo.ProtoReflect.Descriptor instead.
func (*PaymentInfo) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{6}
}

func (x *PaymentInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PaymentInfo) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *PaymentInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PaymentInfo) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *PaymentInfo) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

func (x *PaymentInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentInfo) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *PaymentInfo) GetThirdPartyTxId() string {
	if x != nil {
		return x.ThirdPartyTxId
	}
	return ""
}

func (x *PaymentInfo) GetPaidAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PaidAt
	}
	return nil
}

func (x *PaymentInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PaymentInfo) GetOutTradeNo() string {
	if x != nil {
		return x.OutTradeNo
	}
	return ""
}

func (x *PaymentInfo) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type GetPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentRequest) Reset() {
	*x = GetPaymentRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentRequest) ProtoMessage() {}

func (x *GetPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{7}
}

func (x *GetPaymentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPaymentByOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentByOrderRequest) Reset() {
	*x = GetPaymentByOrderRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentByOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentByOrderRequest) ProtoMessage() {}

func (x *GetPaymentByOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentByOrderRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentByOrderRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{8}
}

func (x *GetPaymentByOrderRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type RefundPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundPaymentRequest) Reset() {
	*x = RefundPaymentRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundPaymentRequest) ProtoMessage() {}

func (x *RefundPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundPaymentRequest.ProtoReflect.Descriptor instead.
func (*RefundPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{9}
}

func (x *RefundPaymentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RefundPaymentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundPaymentReply) Reset() {
	*x = RefundPaymentReply{}
	mi := &file_payment_v1_payment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundPaymentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundPaymentReply) ProtoMessage() {}

func (x *RefundPaymentReply) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundPaymentReply.ProtoReflect.Descriptor instead.
func (*RefundPaymentReply) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{10}
}

type CreatePaymentCheckJobRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PaymentId           int64                  `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	DelaySeconds        int32                  `protobuf:"varint,2,opt,name=delay_seconds,json=delaySeconds,proto3" json:"delay_seconds,omitempty"`
	MaxPolls            int32                  `protobuf:"varint,3,opt,name=max_polls,json=maxPolls,proto3" json:"max_polls,omitempty"`
	PollIntervalSeconds int32                  `protobuf:"varint,4,opt,name=poll_interval_seconds,json=pollIntervalSeconds,proto3" json:"poll_interval_seconds,omitempty"`
	Trigger             string                 `protobuf:"bytes,5,opt,name=trigger,proto3" json:"trigger,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreatePaymentCheckJobRequest) Reset() {
	*x = CreatePaymentCheckJobRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentCheckJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentCheckJobRequest) ProtoMessage() {}

func (x *CreatePaymentCheckJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentCheckJobRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentCheckJobRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{11}
}

func (x *CreatePaymentCheckJobRequest) GetPaymentId() int64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *CreatePaymentCheckJobRequest) GetDelaySeconds() int32 {
	if x != nil {
		return x.DelaySeconds
	}
	return 0
}

func (x *CreatePaymentCheckJobRequest) GetMaxPolls() int32 {
	if x != nil {
		return x.MaxPolls
	}
	return 0
}

func (x *CreatePaymentCheckJobRequest) GetPollIntervalSeconds() int32 {
	if x != nil {
		return x.PollIntervalSeconds
	}
	return 0
}

func (x *CreatePaymentCheckJobRequest) GetTrigger() string {
	if x != nil {
		return x.Trigger
	}
	return ""
}

type GetMQJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMQJobRequest) Reset() {
	*x = GetMQJobRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMQJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMQJobRequest) ProtoMessage() {}

func (x *GetMQJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMQJobRequest.ProtoReflect.Descriptor instead.
func (*GetMQJobRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{12}
}

func (x *GetMQJobRequest) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

type MQJobInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Queue         string                 `protobuf:"bytes,3,opt,name=queue,proto3" json:"queue,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Attempt       int32                  `protobuf:"varint,5,opt,name=attempt,proto3" json:"attempt,omitempty"`
	MaxAttempts   int32                  `protobuf:"varint,6,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	ArgsJson      string                 `protobuf:"bytes,7,opt,name=args_json,json=argsJson,proto3" json:"args_json,omitempty"`
	Tags          []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ScheduledAt   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	AttemptedAt   *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=attempted_at,json=attemptedAt,proto3" json:"attempted_at,omitempty"`
	FinalizedAt   *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=finalized_at,json=finalizedAt,proto3" json:"finalized_at,omitempty"`
	Errors        []*MQJobError          `protobuf:"bytes,13,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MQJobInfo) Reset() {
	*x = MQJobInfo{}
	mi := &file_payment_v1_payment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MQJobInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MQJobInfo) ProtoMessage() {}

func (x *MQJobInfo) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MQJobInfo.ProtoReflect.Descriptor instead.
func (*MQJobInfo) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{13}
}

func (x *MQJobInfo) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *MQJobInfo) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *MQJobInfo) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *MQJobInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *MQJobInfo) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *MQJobInfo) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *MQJobInfo) GetArgsJson() string {
	if x != nil {
		return x.ArgsJson
	}
	return ""
}

func (x *MQJobInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *MQJobInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MQJobInfo) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

func (x *MQJobInfo) GetAttemptedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AttemptedAt
	}
	return nil
}

func (x *MQJobInfo) GetFinalizedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinalizedAt
	}
	return nil
}

func (x *MQJobInfo) GetErrors() []*MQJobError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type MQJobError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attempt       int32                  `protobuf:"varint,1,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	At            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MQJobError) Reset() {
	*x = MQJobError{}
	mi := &file_payment_v1_payment_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MQJobError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MQJobError) ProtoMessage() {}

func (x *MQJobError) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MQJobError.ProtoReflect.Descriptor instead.
func (*MQJobError) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{14}
}

func (x *MQJobError) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *MQJobError) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *MQJobError) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

var File_payment_v1_payment_proto protoreflect.FileDescriptor

const file_payment_v1_payment_proto_rawDesc = "" +
	"\n" +
	"\x18payment/v1/payment.proto\x12\x0eapi.payment.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc1\x02\n" +
	"\x10CreatePaymentReq\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x1b\n" +
	"\tclient_ip\x18\x03 \x01(\tR\bclientIp\x12T\n" +
	"\fextra_params\x18\x04 \x03(\v21.api.payment.v1.CreatePaymentReq.ExtraParamsEntryR\vextraParams\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12%\n" +
	"\ftotal_amount\x18\x06 \x01(\x05B\x02\x18\x01R\vtotalAmount\x1a>\n" +
	"\x10ExtraParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"O\n" +
	"\x12CreatePaymentReply\x12\x1f\n" +
	"\vaction_type\x18\x01 \x01(\tR\n" +
	"actionType\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\"9\n" +
	"\x0fQueryPaymentReq\x12 \n" +
	"\fout_trade_no\x18\x01 \x01(\tR\n" +
	"outTradeNoJ\x04\b\x02\x10\x03\"\xd8\x01\n" +
	"\x11QueryPaymentReply\x12 \n" +
	"\fout_trade_no\x18\x01 \x01(\tR\n" +
	"outTradeNo\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12;\n" +
	"\vtrade_state\x18\x03 \x01(\x0e2\x1a.api.payment.v1.TradeStateR\n" +
	"tradeState\x12!\n" +
	"\famount_minor\x18\x04 \x01(\x03R\vamountMinor\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\"9\n" +
	"\x0fClosePaymentReq\x12 \n" +
	"\fout_trade_no\x18\x01 \x01(\tR\n" +
	"outTradeNoJ\x04\b\x02\x10\x03\"-\n" +
	"\x11ClosePaymentReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x9e\x03\n" +
	"\vPaymentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vmerchant_id\x18\x04 \x01(\x03R\n" +
	"merchantId\x12!\n" +
	"\famount_minor\x18\x05 \x01(\x03R\vamountMinor\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x16\n" +
	"\x06method\x18\a \x01(\tR\x06method\x12)\n" +
	"\x11third_party_tx_id\x18\b \x01(\tR\x0ethirdPartyTxId\x123\n" +
	"\apaid_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x06paidAt\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12 \n" +
	"\fout_trade_no\x18\v \x01(\tR\n" +
	"outTradeNo\x12\x1a\n" +
	"\bcurrency\x18\f \x01(\tR\bcurrency\"#\n" +
	"\x11GetPaymentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"5\n" +
	"\x18GetPaymentByOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\"&\n" +
	"\x14RefundPaymentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x14\n" +
	"\x12RefundPaymentReply\"\xcd\x01\n" +
	"\x1cCreatePaymentCheckJobRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\x03R\tpaymentId\x12#\n" +
	"\rdelay_seconds\x18\x02 \x01(\x05R\fdelaySeconds\x12\x1b\n" +
	"\tmax_polls\x18\x03 \x01(\x05R\bmaxPolls\x122\n" +
	"\x15poll_interval_seconds\x18\x04 \x01(\x05R\x13pollIntervalSeconds\x12\x18\n" +
	"\atrigger\x18\x05 \x01(\tR\atrigger\"(\n" +
	"\x0fGetMQJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\"\xfc\x03\n" +
	"\tMQJobInfo\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x14\n" +
	"\x05queue\x18\x03 \x01(\tR\x05queue\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x18\n" +
	"\aattempt\x18\x05 \x01(\x05R\aattempt\x12!\n" +
	"\fmax_attempts\x18\x06 \x01(\x05R\vmaxAttempts\x12\x1b\n" +
	"\targs_json\x18\a \x01(\tR\bargsJson\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fscheduled_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\x12=\n" +
	"\fattempted_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vattemptedAt\x12=\n" +
	"\ffinalized_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\vfinalizedAt\x122\n" +
	"\x06errors\x18\r \x03(\v2\x1a.api.payment.v1.MQJobErrorR\x06errors\"h\n" +
	"\n" +
	"MQJobError\x12\x18\n" +
	"\aattempt\x18\x01 \x01(\x05R\aattempt\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12*\n" +
	"\x02at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02at*\x85\x01\n" +
	"\n" +
	"TradeState\x12\x1b\n" +
	"\x17TRADE_STATE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\n" +
	"\n" +
	"\x06REFUND\x10\x02\x12\n" +
	"\n" +
	"\x06NOTPAY\x10\x03\x12\n" +
	"\n" +
	"\x06CLOSED\x10\x04\x12\v\n" +
	"\aREVOKED\x10\x05\x12\x0e\n" +
	"\n" +
	"USERPAYING\x10\x06\x12\f\n" +
	"\bPAYERROR\x10\a2\xd0\a\n" +
	"\aPayment\x12n\n" +
	"\rCreatePayment\x12 .api.payment.v1.CreatePaymentReq\x1a\".api.payment.v1.CreatePaymentReply\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/payments\x12o\n" +
	"\fQueryPayment\x12\x1f.api.payment.v1.QueryPaymentReq\x1a!.api.payment.v1.QueryPaymentReply\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/payments/lookup\x12x\n" +
	"\fClosePayment\x12\x1f.api.payment.v1.ClosePaymentReq\x1a!.api.payment.v1.ClosePaymentReply\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/payments/lookup/close\x12g\n" +
	"\n" +
	"GetPayment\x12!.api.payment.v1.GetPaymentRequest\x1a\x1b.api.payment.v1.PaymentInfo\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/payments/{id}\x12\x81\x01\n" +
	"\x11GetPaymentByOrder\x12(.api.payment.v1.GetPaymentByOrderRequest\x1a\x1b.api.payment.v1.PaymentInfo\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/orders/{order_id}/payment\x12~\n" +
	"\rRefundPayment\x12$.api.payment.v1.RefundPaymentRequest\x1a\".api.payment.v1.RefundPaymentReply\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/payments/{id}/refund\x12\x8d\x01\n" +
	"\x15CreatePaymentCheckJob\x12,.api.payment.v1.CreatePaymentCheckJobRequest\x1a\x19.api.payment.v1.MQJobInfo\"+\x82\xd3\xe4\x93\x02%:\x01*\" /v1/payments/{payment_id}/checks\x12m\n" +
	"\bGetMQJob\x12\x1f.api.payment.v1.GetMQJobRequest\x1a\x19.api.payment.v1.MQJobInfo\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/payments/mq/jobs/{job_id}BM\n" +
	"\x0eapi.payment.v1P\x01Z9github.com/Dailiduzhou/simple-ecommerce/api/payment/v1;v1b\x06proto3"

var (
	file_payment_v1_payment_proto_rawDescOnce sync.Once
	file_payment_v1_payment_proto_rawDescData []byte
)

func file_payment_v1_payment_proto_rawDescGZIP() []byte {
	file_payment_v1_payment_proto_rawDescOnce.Do(func() {
		file_payment_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_v1_payment_proto_rawDesc), len(file_payment_v1_payment_proto_rawDesc)))
	})
	return file_payment_v1_payment_proto_rawDescData
}

var file_payment_v1_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_payment_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_payment_v1_payment_proto_goTypes = []any{
	(TradeState)(0),                      // 0: api.payment.v1.TradeState
	(*CreatePaymentReq)(nil),             // 1: api.payment.v1.CreatePaymentReq
	(*CreatePaymentReply)(nil),           // 2: api.payment.v1.CreatePaymentReply
	(*QueryPaymentReq)(nil),              // 3: api.payment.v1.QueryPaymentReq
	(*QueryPaymentReply)(nil),            // 4: api.payment.v1.QueryPaymentReply
	(*ClosePaymentReq)(nil),              // 5: api.payment.v1.ClosePaymentReq
	(*ClosePaymentReply)(nil),            // 6: api.payment.v1.ClosePaymentReply
	(*PaymentInfo)(nil),                  // 7: api.payment.v1.PaymentInfo
	(*GetPaymentRequest)(nil),            // 8: api.payment.v1.GetPaymentRequest
	(*GetPaymentByOrderRequest)(nil),     // 9: api.payment.v1.GetPaymentByOrderRequest
	(*RefundPaymentRequest)(nil),         // 10: api.payment.v1.RefundPaymentRequest
	(*RefundPaymentReply)(nil),           // 11: api.payment.v1.RefundPaymentReply
	(*CreatePaymentCheckJobRequest)(nil), // 12: api.payment.v1.CreatePaymentCheckJobRequest
	(*GetMQJobRequest)(nil),              // 13: api.payment.v1.GetMQJobRequest
	(*MQJobInfo)(nil),                    // 14: api.payment.v1.MQJobInfo
	(*MQJobError)(nil),                   // 15: api.payment.v1.MQJobError
	nil,                                  // 16: api.payment.v1.CreatePaymentReq.ExtraParamsEntry
	(*timestamppb.Timestamp)(nil),        // 17: google.protobuf.Timestamp
}
var file_payment_v1_payment_proto_depIdxs = []int32{
	16, // 0: api.payment.v1.CreatePaymentReq.extra_params:type_name -> api.payment.v1.CreatePaymentReq.ExtraParamsEntry
	0,  // 1: api.payment.v1.QueryPaymentReply.trade_state:type_name -> api.payment.v1.TradeState
	17, // 2: api.payment.v1.PaymentInfo.paid_at:type_name -> google.protobuf.Timestamp
	17, // 3: api.payment.v1.PaymentInfo.created_at:type_name -> google.protobuf.Timestamp
	17, // 4: api.payment.v1.MQJobInfo.created_at:type_name -> google.protobuf.Timestamp
	17, // 5: api.payment.v1.MQJobInfo.scheduled_at:type_name -> google.protobuf.Timestamp
	17, // 6: api.payment.v1.MQJobInfo.attempted_at:type_name -> google.protobuf.Timestamp
	17, // 7: api.payment.v1.MQJobInfo.finalized_at:type_name -> google.protobuf.Timestamp
	15, // 8: api.payment.v1.MQJobInfo.errors:type_name -> api.payment.v1.MQJobError
	17, // 9: api.payment.v1.MQJobError.at:type_name -> google.protobuf.Timestamp
	1,  // 10: api.payment.v1.Payment.CreatePayment:input_type -> api.payment.v1.CreatePaymentReq
	3,  // 11: api.payment.v1.Payment.QueryPayment:input_type -> api.payment.v1.QueryPaymentReq
	5,  // 12: api.payment.v1.Payment.ClosePayment:input_type -> api.payment.v1.ClosePaymentReq
	8,  // 13: api.payment.v1.Payment.GetPayment:input_type -> api.payment.v1.GetPaymentRequest
	9,  // 14: api.payment.v1.Payment.GetPaymentByOrder:input_type -> api.payment.v1.GetPaymentByOrderRequest
	10, // 15: api.payment.v1.Payment.RefundPayment:input_type -> api.payment.v1.RefundPaymentRequest
	12, // 16: api.payment.v1.Payment.CreatePaymentCheckJob:input_type -> api.payment.v1.CreatePaymentCheckJobRequest
	13, // 17: api.payment.v1.Payment.GetMQJob:input_type -> api.payment.v1.GetMQJobRequest
	2,  // 18: api.payment.v1.Payment.CreatePayment:output_type -> api.payment.v1.CreatePaymentReply
	4,  // 19: api.payment.v1.Payment.QueryPayment:output_type -> api.payment.v1.QueryPaymentReply
	6,  // 20: api.payment.v1.Payment.ClosePayment:output_type -> api.payment.v1.ClosePaymentReply
	7,  // 21: api.payment.v1.Payment.GetPayment:output_type -> api.payment.v1.PaymentInfo
	7,  // 22: api.payment.v1.Payment.GetPaymentByOrder:output_type -> api.payment.v1.PaymentInfo
	11, // 23: api.payment.v1.Payment.RefundPayment:output_type -> api.payment.v1.RefundPaymentReply
	14, // 24: api.payment.v1.Payment.CreatePaymentCheckJob:output_type -> api.payment.v1.MQJobInfo
	14, // 25: api.payment.v1.Payment.GetMQJob:output_type -> api.payment.v1.MQJobInfo
	18, // [18:26] is the sub-list for method output_type
	10, // [10:18] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_payment_v1_payment_proto_init() }
func file_payment_v1_payment_proto_init() {
	if File_payment_v1_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_v1_payment_proto_rawDesc), len(file_payment_v1_payment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_v1_payment_proto_goTypes,
		DependencyIndexes: file_payment_v1_payment_proto_depIdxs,
		EnumInfos:         file_payment_v1_payment_proto_enumTypes,
		MessageInfos:      file_payment_v1_payment_proto_msgTypes,
	}.Build()
	File_payment_v1_payment_proto = out.File
	file_payment_v1_payment_proto_goTypes = nil
	file_payment_v1_payment_proto_depIdxs = nil
}
