// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: api/payment/v1/payment.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 微信支付交易状态枚举
type TradeState int32

const (
	TradeState_TRADE_STATE_UNSPECIFIED TradeState = 0
	TradeState_SUCCESS                 TradeState = 1 // 支付成功
	TradeState_REFUND                  TradeState = 2 // 转入退款
	TradeState_NOTPAY                  TradeState = 3 // 未支付
	TradeState_CLOSED                  TradeState = 4 // 已关闭
	TradeState_REVOKED                 TradeState = 5 // 已撤销
	TradeState_USERPAYING              TradeState = 6 // 用户支付中
	TradeState_PAYERROR                TradeState = 7 // 支付失败
)

// Enum value maps for TradeState.
var (
	TradeState_name = map[int32]string{
		0: "TRADE_STATE_UNSPECIFIED",
		1: "SUCCESS",
		2: "REFUND",
		3: "NOTPAY",
		4: "CLOSED",
		5: "REVOKED",
		6: "USERPAYING",
		7: "PAYERROR",
	}
	TradeState_value = map[string]int32{
		"TRADE_STATE_UNSPECIFIED": 0,
		"SUCCESS":                 1,
		"REFUND":                  2,
		"NOTPAY":                  3,
		"CLOSED":                  4,
		"REVOKED":                 5,
		"USERPAYING":              6,
		"PAYERROR":                7,
	}
)

func (x TradeState) Enum() *TradeState {
	p := new(TradeState)
	*p = x
	return p
}

func (x TradeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TradeState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_payment_v1_payment_proto_enumTypes[0].Descriptor()
}

func (TradeState) Type() protoreflect.EnumType {
	return &file_api_payment_v1_payment_proto_enumTypes[0]
}

func (x TradeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TradeState.Descriptor instead.
func (TradeState) EnumDescriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

type PaymentInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId        int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId         int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MerchantId     int64                  `protobuf:"varint,4,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Amount         string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // pending/success/failed/refunded
	PayChannel     string                 `protobuf:"bytes,7,opt,name=pay_channel,json=payChannel,proto3" json:"pay_channel,omitempty"`
	ThirdPartyTxId string                 `protobuf:"bytes,8,opt,name=third_party_tx_id,json=thirdPartyTxId,proto3" json:"third_party_tx_id,omitempty"`
	PaidAt         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PaymentInfo) Reset() {
	*x = PaymentInfo{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentInfo) ProtoMessage() {}

func (x *PaymentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentInfo.ProtoReflect.Descriptor instead.
func (*PaymentInfo) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PaymentInfo) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *PaymentInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PaymentInfo) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *PaymentInfo) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *PaymentInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentInfo) GetPayChannel() string {
	if x != nil {
		return x.PayChannel
	}
	return ""
}

func (x *PaymentInfo) GetThirdPartyTxId() string {
	if x != nil {
		return x.ThirdPartyTxId
	}
	return ""
}

func (x *PaymentInfo) GetPaidAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PaidAt
	}
	return nil
}

func (x *PaymentInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MerchantId    int64                  `protobuf:"varint,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	PayChannel    string                 `protobuf:"bytes,4,opt,name=pay_channel,json=payChannel,proto3" json:"pay_channel,omitempty"` // wechat/alipay
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CreatePaymentRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreatePaymentRequest) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *CreatePaymentRequest) GetPayChannel() string {
	if x != nil {
		return x.PayChannel
	}
	return ""
}

type GetPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentRequest) Reset() {
	*x = GetPaymentRequest{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentRequest) ProtoMessage() {}

func (x *GetPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentRequest) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{2}
}

func (x *GetPaymentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPaymentByOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentByOrderRequest) Reset() {
	*x = GetPaymentByOrderRequest{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentByOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentByOrderRequest) ProtoMessage() {}

func (x *GetPaymentByOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentByOrderRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentByOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{3}
}

func (x *GetPaymentByOrderRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type NotifyPaymentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ThirdPartyTxId string                 `protobuf:"bytes,1,opt,name=third_party_tx_id,json=thirdPartyTxId,proto3" json:"third_party_tx_id,omitempty"`
	PayChannel     string                 `protobuf:"bytes,2,opt,name=pay_channel,json=payChannel,proto3" json:"pay_channel,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // success/failed
	PaymentId      int64                  `protobuf:"varint,4,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotifyPaymentRequest) Reset() {
	*x = NotifyPaymentRequest{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyPaymentRequest) ProtoMessage() {}

func (x *NotifyPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyPaymentRequest.ProtoReflect.Descriptor instead.
func (*NotifyPaymentRequest) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{4}
}

func (x *NotifyPaymentRequest) GetThirdPartyTxId() string {
	if x != nil {
		return x.ThirdPartyTxId
	}
	return ""
}

func (x *NotifyPaymentRequest) GetPayChannel() string {
	if x != nil {
		return x.PayChannel
	}
	return ""
}

func (x *NotifyPaymentRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NotifyPaymentRequest) GetPaymentId() int64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

type NotifyPaymentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` // "success" 告知第三方已处理
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyPaymentReply) Reset() {
	*x = NotifyPaymentReply{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyPaymentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyPaymentReply) ProtoMessage() {}

func (x *NotifyPaymentReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyPaymentReply.ProtoReflect.Descriptor instead.
func (*NotifyPaymentReply) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{5}
}

func (x *NotifyPaymentReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type RefundPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundPaymentRequest) Reset() {
	*x = RefundPaymentRequest{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundPaymentRequest) ProtoMessage() {}

func (x *RefundPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundPaymentRequest.ProtoReflect.Descriptor instead.
func (*RefundPaymentRequest) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{6}
}

func (x *RefundPaymentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RefundPaymentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundPaymentReply) Reset() {
	*x = RefundPaymentReply{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundPaymentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundPaymentReply) ProtoMessage() {}

func (x *RefundPaymentReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundPaymentReply.ProtoReflect.Descriptor instead.
func (*RefundPaymentReply) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{7}
}

type CreateWechatPayCheckJobRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PaymentId           int64                  `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	OrderId             int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OutTradeNo          string                 `protobuf:"bytes,3,opt,name=out_trade_no,json=outTradeNo,proto3" json:"out_trade_no,omitempty"`
	DelaySeconds        int32                  `protobuf:"varint,4,opt,name=delay_seconds,json=delaySeconds,proto3" json:"delay_seconds,omitempty"`
	MaxPolls            int32                  `protobuf:"varint,5,opt,name=max_polls,json=maxPolls,proto3" json:"max_polls,omitempty"`
	PollIntervalSeconds int32                  `protobuf:"varint,6,opt,name=poll_interval_seconds,json=pollIntervalSeconds,proto3" json:"poll_interval_seconds,omitempty"`
	Source              string                 `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateWechatPayCheckJobRequest) Reset() {
	*x = CreateWechatPayCheckJobRequest{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWechatPayCheckJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWechatPayCheckJobRequest) ProtoMessage() {}

func (x *CreateWechatPayCheckJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWechatPayCheckJobRequest.ProtoReflect.Descriptor instead.
func (*CreateWechatPayCheckJobRequest) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{8}
}

func (x *CreateWechatPayCheckJobRequest) GetPaymentId() int64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *CreateWechatPayCheckJobRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CreateWechatPayCheckJobRequest) GetOutTradeNo() string {
	if x != nil {
		return x.OutTradeNo
	}
	return ""
}

func (x *CreateWechatPayCheckJobRequest) GetDelaySeconds() int32 {
	if x != nil {
		return x.DelaySeconds
	}
	return 0
}

func (x *CreateWechatPayCheckJobRequest) GetMaxPolls() int32 {
	if x != nil {
		return x.MaxPolls
	}
	return 0
}

func (x *CreateWechatPayCheckJobRequest) GetPollIntervalSeconds() int32 {
	if x != nil {
		return x.PollIntervalSeconds
	}
	return 0
}

func (x *CreateWechatPayCheckJobRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type GetMQJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMQJobRequest) Reset() {
	*x = GetMQJobRequest{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMQJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMQJobRequest) ProtoMessage() {}

func (x *GetMQJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMQJobRequest.ProtoReflect.Descriptor instead.
func (*GetMQJobRequest) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{9}
}

func (x *GetMQJobRequest) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

type MQJobInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Queue         string                 `protobuf:"bytes,3,opt,name=queue,proto3" json:"queue,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Attempt       int32                  `protobuf:"varint,5,opt,name=attempt,proto3" json:"attempt,omitempty"`
	MaxAttempts   int32                  `protobuf:"varint,6,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	ArgsJson      string                 `protobuf:"bytes,7,opt,name=args_json,json=argsJson,proto3" json:"args_json,omitempty"`
	Tags          []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ScheduledAt   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	AttemptedAt   *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=attempted_at,json=attemptedAt,proto3" json:"attempted_at,omitempty"`
	FinalizedAt   *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=finalized_at,json=finalizedAt,proto3" json:"finalized_at,omitempty"`
	Errors        []*MQJobError          `protobuf:"bytes,13,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MQJobInfo) Reset() {
	*x = MQJobInfo{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MQJobInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MQJobInfo) ProtoMessage() {}

func (x *MQJobInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MQJobInfo.ProtoReflect.Descriptor instead.
func (*MQJobInfo) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{10}
}

func (x *MQJobInfo) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *MQJobInfo) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *MQJobInfo) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *MQJobInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *MQJobInfo) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *MQJobInfo) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *MQJobInfo) GetArgsJson() string {
	if x != nil {
		return x.ArgsJson
	}
	return ""
}

func (x *MQJobInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *MQJobInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MQJobInfo) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

func (x *MQJobInfo) GetAttemptedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AttemptedAt
	}
	return nil
}

func (x *MQJobInfo) GetFinalizedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinalizedAt
	}
	return nil
}

func (x *MQJobInfo) GetErrors() []*MQJobError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type MQJobError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attempt       int32                  `protobuf:"varint,1,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	At            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MQJobError) Reset() {
	*x = MQJobError{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MQJobError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MQJobError) ProtoMessage() {}

func (x *MQJobError) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MQJobError.ProtoReflect.Descriptor instead.
func (*MQJobError) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{11}
}

func (x *MQJobError) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *MQJobError) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *MQJobError) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

// JSAPI 统一下单请求
type PrepayJSAPIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutTradeNo    string                 `protobuf:"bytes,1,opt,name=out_trade_no,json=outTradeNo,proto3" json:"out_trade_no,omitempty"`   // 商户订单号
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`                     // 商品描述
	TotalAmount   int32                  `protobuf:"varint,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"` // 订单总金额，单位为分
	Openid        string                 `protobuf:"bytes,4,opt,name=openid,proto3" json:"openid,omitempty"`                               // 用户在商户 appid 下的唯一标识
	PayChannel    string                 `protobuf:"bytes,5,opt,name=pay_channel,json=payChannel,proto3" json:"pay_channel,omitempty"`     // 支付渠道 (wechat/alipay)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepayJSAPIRequest) Reset() {
	*x = PrepayJSAPIRequest{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepayJSAPIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepayJSAPIRequest) ProtoMessage() {}

func (x *PrepayJSAPIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepayJSAPIRequest.ProtoReflect.Descriptor instead.
func (*PrepayJSAPIRequest) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{12}
}

func (x *PrepayJSAPIRequest) GetOutTradeNo() string {
	if x != nil {
		return x.OutTradeNo
	}
	return ""
}

func (x *PrepayJSAPIRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PrepayJSAPIRequest) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *PrepayJSAPIRequest) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

func (x *PrepayJSAPIRequest) GetPayChannel() string {
	if x != nil {
		return x.PayChannel
	}
	return ""
}

// JSAPI 统一下单响应 (返回给前端唤起微信支付的核心参数)
type PrepayJSAPIReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`                   // 应用ID
	TimeStamp     string                 `protobuf:"bytes,2,opt,name=time_stamp,json=timeStamp,proto3" json:"time_stamp,omitempty"`       // 时间戳
	NonceStr      string                 `protobuf:"bytes,3,opt,name=nonce_str,json=nonceStr,proto3" json:"nonce_str,omitempty"`          // 随机字符串
	PrepayPackage string                 `protobuf:"bytes,4,opt,name=prepay_package,json=package,proto3" json:"prepay_package,omitempty"` // 订单详情扩展字符串 (如 prepay_id=xxx)
	SignType      string                 `protobuf:"bytes,5,opt,name=sign_type,json=signType,proto3" json:"sign_type,omitempty"`          // 签名方式 (通常是 RSA)
	PaySign       string                 `protobuf:"bytes,6,opt,name=pay_sign,json=paySign,proto3" json:"pay_sign,omitempty"`             // 签名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepayJSAPIReply) Reset() {
	*x = PrepayJSAPIReply{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepayJSAPIReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepayJSAPIReply) ProtoMessage() {}

func (x *PrepayJSAPIReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepayJSAPIReply.ProtoReflect.Descriptor instead.
func (*PrepayJSAPIReply) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{13}
}

func (x *PrepayJSAPIReply) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *PrepayJSAPIReply) GetTimeStamp() string {
	if x != nil {
		return x.TimeStamp
	}
	return ""
}

func (x *PrepayJSAPIReply) GetNonceStr() string {
	if x != nil {
		return x.NonceStr
	}
	return ""
}

func (x *PrepayJSAPIReply) GetPrepayPackage() string {
	if x != nil {
		return x.PrepayPackage
	}
	return ""
}

func (x *PrepayJSAPIReply) GetSignType() string {
	if x != nil {
		return x.SignType
	}
	return ""
}

func (x *PrepayJSAPIReply) GetPaySign() string {
	if x != nil {
		return x.PaySign
	}
	return ""
}

// 查询订单请求
type QueryOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutTradeNo    string                 `protobuf:"bytes,1,opt,name=out_trade_no,json=outTradeNo,proto3" json:"out_trade_no,omitempty"` // 商户订单号
	PayChannel    string                 `protobuf:"bytes,2,opt,name=pay_channel,json=payChannel,proto3" json:"pay_channel,omitempty"`   // 支付渠道 (wechat/alipay)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryOrderRequest) Reset() {
	*x = QueryOrderRequest{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOrderRequest) ProtoMessage() {}

func (x *QueryOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOrderRequest.ProtoReflect.Descriptor instead.
func (*QueryOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{14}
}

func (x *QueryOrderRequest) GetOutTradeNo() string {
	if x != nil {
		return x.OutTradeNo
	}
	return ""
}

func (x *QueryOrderRequest) GetPayChannel() string {
	if x != nil {
		return x.PayChannel
	}
	return ""
}

// 查询订单响应
type QueryOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutTradeNo    string                 `protobuf:"bytes,1,opt,name=out_trade_no,json=outTradeNo,proto3" json:"out_trade_no,omitempty"`                               // 商户订单号
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`                        // 微信支付系统生成的订单号
	TradeState    TradeState             `protobuf:"varint,3,opt,name=trade_state,json=tradeState,proto3,enum=api.payment.v1.TradeState" json:"trade_state,omitempty"` // 交易状态
	TotalAmount   int32                  `protobuf:"varint,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`                             // 订单总金额，单位为分
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryOrderReply) Reset() {
	*x = QueryOrderReply{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOrderReply) ProtoMessage() {}

func (x *QueryOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOrderReply.ProtoReflect.Descriptor instead.
func (*QueryOrderReply) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{15}
}

func (x *QueryOrderReply) GetOutTradeNo() string {
	if x != nil {
		return x.OutTradeNo
	}
	return ""
}

func (x *QueryOrderReply) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *QueryOrderReply) GetTradeState() TradeState {
	if x != nil {
		return x.TradeState
	}
	return TradeState_TRADE_STATE_UNSPECIFIED
}

func (x *QueryOrderReply) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

// 关闭订单请求
type CloseOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutTradeNo    string                 `protobuf:"bytes,1,opt,name=out_trade_no,json=outTradeNo,proto3" json:"out_trade_no,omitempty"` // 商户订单号
	PayChannel    string                 `protobuf:"bytes,2,opt,name=pay_channel,json=payChannel,proto3" json:"pay_channel,omitempty"`   // 支付渠道 (wechat/alipay)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseOrderRequest) Reset() {
	*x = CloseOrderRequest{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseOrderRequest) ProtoMessage() {}

func (x *CloseOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseOrderRequest.ProtoReflect.Descriptor instead.
func (*CloseOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{16}
}

func (x *CloseOrderRequest) GetOutTradeNo() string {
	if x != nil {
		return x.OutTradeNo
	}
	return ""
}

func (x *CloseOrderRequest) GetPayChannel() string {
	if x != nil {
		return x.PayChannel
	}
	return ""
}

// 关闭订单响应
type CloseOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否关闭成功
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseOrderReply) Reset() {
	*x = CloseOrderReply{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseOrderReply) ProtoMessage() {}

func (x *CloseOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseOrderReply.ProtoReflect.Descriptor instead.
func (*CloseOrderReply) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{17}
}

func (x *CloseOrderReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_payment_v1_payment_proto protoreflect.FileDescriptor

const file_api_payment_v1_payment_proto_rawDesc = "" +
	"\n" +
	"\x1capi/payment/v1/payment.proto\x12\x0eapi.payment.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xde\x02\n" +
	"\vPaymentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vmerchant_id\x18\x04 \x01(\x03R\n" +
	"merchantId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1f\n" +
	"\vpay_channel\x18\a \x01(\tR\n" +
	"payChannel\x12)\n" +
	"\x11third_party_tx_id\x18\b \x01(\tR\x0ethirdPartyTxId\x123\n" +
	"\apaid_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x06paidAt\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x8c\x01\n" +
	"\x14CreatePaymentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\x03R\n" +
	"merchantId\x12\x1f\n" +
	"\vpay_channel\x18\x04 \x01(\tR\n" +
	"payChannel\"#\n" +
	"\x11GetPaymentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"5\n" +
	"\x18GetPaymentByOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\"\x99\x01\n" +
	"\x14NotifyPaymentRequest\x12)\n" +
	"\x11third_party_tx_id\x18\x01 \x01(\tR\x0ethirdPartyTxId\x12\x1f\n" +
	"\vpay_channel\x18\x02 \x01(\tR\n" +
	"payChannel\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x04 \x01(\x03R\tpaymentId\",\n" +
	"\x12NotifyPaymentReply\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"&\n" +
	"\x14RefundPaymentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x14\n" +
	"\x12RefundPaymentReply\"\x8a\x02\n" +
	"\x1eCreateWechatPayCheckJobRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\x03R\tpaymentId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12 \n" +
	"\fout_trade_no\x18\x03 \x01(\tR\n" +
	"outTradeNo\x12#\n" +
	"\rdelay_seconds\x18\x04 \x01(\x05R\fdelaySeconds\x12\x1b\n" +
	"\tmax_polls\x18\x05 \x01(\x05R\bmaxPolls\x122\n" +
	"\x15poll_interval_seconds\x18\x06 \x01(\x05R\x13pollIntervalSeconds\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\"(\n" +
	"\x0fGetMQJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\"\xfc\x03\n" +
	"\tMQJobInfo\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x14\n" +
	"\x05queue\x18\x03 \x01(\tR\x05queue\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x18\n" +
	"\aattempt\x18\x05 \x01(\x05R\aattempt\x12!\n" +
	"\fmax_attempts\x18\x06 \x01(\x05R\vmaxAttempts\x12\x1b\n" +
	"\targs_json\x18\a \x01(\tR\bargsJson\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fscheduled_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\x12=\n" +
	"\fattempted_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vattemptedAt\x12=\n" +
	"\ffinalized_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\vfinalizedAt\x122\n" +
	"\x06errors\x18\r \x03(\v2\x1a.api.payment.v1.MQJobErrorR\x06errors\"h\n" +
	"\n" +
	"MQJobError\x12\x18\n" +
	"\aattempt\x18\x01 \x01(\x05R\aattempt\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12*\n" +
	"\x02at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\"\xb4\x01\n" +
	"\x12PrepayJSAPIRequest\x12 \n" +
	"\fout_trade_no\x18\x01 \x01(\tR\n" +
	"outTradeNo\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x05R\vtotalAmount\x12\x16\n" +
	"\x06openid\x18\x04 \x01(\tR\x06openid\x12\x1f\n" +
	"\vpay_channel\x18\x05 \x01(\tR\n" +
	"payChannel\"\xbe\x01\n" +
	"\x10PrepayJSAPIReply\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1d\n" +
	"\n" +
	"time_stamp\x18\x02 \x01(\tR\ttimeStamp\x12\x1b\n" +
	"\tnonce_str\x18\x03 \x01(\tR\bnonceStr\x12\x1f\n" +
	"\x0eprepay_package\x18\x04 \x01(\tR\apackage\x12\x1b\n" +
	"\tsign_type\x18\x05 \x01(\tR\bsignType\x12\x19\n" +
	"\bpay_sign\x18\x06 \x01(\tR\apaySign\"V\n" +
	"\x11QueryOrderRequest\x12 \n" +
	"\fout_trade_no\x18\x01 \x01(\tR\n" +
	"outTradeNo\x12\x1f\n" +
	"\vpay_channel\x18\x02 \x01(\tR\n" +
	"payChannel\"\xba\x01\n" +
	"\x0fQueryOrderReply\x12 \n" +
	"\fout_trade_no\x18\x01 \x01(\tR\n" +
	"outTradeNo\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12;\n" +
	"\vtrade_state\x18\x03 \x01(\x0e2\x1a.api.payment.v1.TradeStateR\n" +
	"tradeState\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x05R\vtotalAmount\"V\n" +
	"\x11CloseOrderRequest\x12 \n" +
	"\fout_trade_no\x18\x01 \x01(\tR\n" +
	"outTradeNo\x12\x1f\n" +
	"\vpay_channel\x18\x02 \x01(\tR\n" +
	"payChannel\"+\n" +
	"\x0fCloseOrderReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*\x85\x01\n" +
	"\n" +
	"TradeState\x12\x1b\n" +
	"\x17TRADE_STATE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\n" +
	"\n" +
	"\x06REFUND\x10\x02\x12\n" +
	"\n" +
	"\x06NOTPAY\x10\x03\x12\n" +
	"\n" +
	"\x06CLOSED\x10\x04\x12\v\n" +
	"\aREVOKED\x10\x05\x12\x0e\n" +
	"\n" +
	"USERPAYING\x10\x06\x12\f\n" +
	"\bPAYERROR\x10\a2\xd6\x06\n" +
	"\aPayment\x12k\n" +
	"\rCreatePayment\x12$.api.payment.v1.CreatePaymentRequest\x1a\x1b.api.payment.v1.PaymentInfo\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/payments\x12g\n" +
	"\n" +
	"GetPayment\x12!.api.payment.v1.GetPaymentRequest\x1a\x1b.api.payment.v1.PaymentInfo\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/payments/{id}\x12\x81\x01\n" +
	"\x11GetPaymentByOrder\x12(.api.payment.v1.GetPaymentByOrderRequest\x1a\x1b.api.payment.v1.PaymentInfo\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/orders/{order_id}/payment\x12y\n" +
	"\rNotifyPayment\x12$.api.payment.v1.NotifyPaymentRequest\x1a\".api.payment.v1.NotifyPaymentReply\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/payments/notify\x12~\n" +
	"\rRefundPayment\x12$.api.payment.v1.RefundPaymentRequest\x1a\".api.payment.v1.RefundPaymentReply\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/payments/{id}/refund\x12\x86\x01\n" +
	"\x17CreateWechatPayCheckJob\x12..api.payment.v1.CreateWechatPayCheckJobRequest\x1a\x19.api.payment.v1.MQJobInfo\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/pay/wechat/checks\x12m\n" +
	"\bGetMQJob\x12\x1f.api.payment.v1.GetMQJobRequest\x1a\x19.api.payment.v1.MQJobInfo\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/payments/mq/jobs/{job_id}2\x97\x03\n" +
	"\x10WechatPayService\x12{\n" +
	"\vPrepayJSAPI\x12\".api.payment.v1.PrepayJSAPIRequest\x1a .api.payment.v1.PrepayJSAPIReply\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/pay/wechat/prepay/jsapi\x12}\n" +
	"\n" +
	"QueryOrder\x12!.api.payment.v1.QueryOrderRequest\x1a\x1f.api.payment.v1.QueryOrderReply\"+\x82\xd3\xe4\x93\x02%\x12#/v1/pay/wechat/order/{out_trade_no}\x12\x86\x01\n" +
	"\n" +
	"CloseOrder\x12!.api.payment.v1.CloseOrderRequest\x1a\x1f.api.payment.v1.CloseOrderReply\"4\x82\xd3\xe4\x93\x02.:\x01*\")/v1/pay/wechat/order/{out_trade_no}/closeBM\n" +
	"\x0eapi.payment.v1P\x01Z9github.com/Dailiduzhou/simple-ecommerce/api/payment/v1;v1b\x06proto3"

var (
	file_api_payment_v1_payment_proto_rawDescOnce sync.Once
	file_api_payment_v1_payment_proto_rawDescData []byte
)

func file_api_payment_v1_payment_proto_rawDescGZIP() []byte {
	file_api_payment_v1_payment_proto_rawDescOnce.Do(func() {
		file_api_payment_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_payment_v1_payment_proto_rawDesc), len(file_api_payment_v1_payment_proto_rawDesc)))
	})
	return file_api_payment_v1_payment_proto_rawDescData
}

var file_api_payment_v1_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_payment_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_payment_v1_payment_proto_goTypes = []any{
	(TradeState)(0),                        // 0: api.payment.v1.TradeState
	(*PaymentInfo)(nil),                    // 1: api.payment.v1.PaymentInfo
	(*CreatePaymentRequest)(nil),           // 2: api.payment.v1.CreatePaymentRequest
	(*GetPaymentRequest)(nil),              // 3: api.payment.v1.GetPaymentRequest
	(*GetPaymentByOrderRequest)(nil),       // 4: api.payment.v1.GetPaymentByOrderRequest
	(*NotifyPaymentRequest)(nil),           // 5: api.payment.v1.NotifyPaymentRequest
	(*NotifyPaymentReply)(nil),             // 6: api.payment.v1.NotifyPaymentReply
	(*RefundPaymentRequest)(nil),           // 7: api.payment.v1.RefundPaymentRequest
	(*RefundPaymentReply)(nil),             // 8: api.payment.v1.RefundPaymentReply
	(*CreateWechatPayCheckJobRequest)(nil), // 9: api.payment.v1.CreateWechatPayCheckJobRequest
	(*GetMQJobRequest)(nil),                // 10: api.payment.v1.GetMQJobRequest
	(*MQJobInfo)(nil),                      // 11: api.payment.v1.MQJobInfo
	(*MQJobError)(nil),                     // 12: api.payment.v1.MQJobError
	(*PrepayJSAPIRequest)(nil),             // 13: api.payment.v1.PrepayJSAPIRequest
	(*PrepayJSAPIReply)(nil),               // 14: api.payment.v1.PrepayJSAPIReply
	(*QueryOrderRequest)(nil),              // 15: api.payment.v1.QueryOrderRequest
	(*QueryOrderReply)(nil),                // 16: api.payment.v1.QueryOrderReply
	(*CloseOrderRequest)(nil),              // 17: api.payment.v1.CloseOrderRequest
	(*CloseOrderReply)(nil),                // 18: api.payment.v1.CloseOrderReply
	(*timestamppb.Timestamp)(nil),          // 19: google.protobuf.Timestamp
}
var file_api_payment_v1_payment_proto_depIdxs = []int32{
	19, // 0: api.payment.v1.PaymentInfo.paid_at:type_name -> google.protobuf.Timestamp
	19, // 1: api.payment.v1.PaymentInfo.created_at:type_name -> google.protobuf.Timestamp
	19, // 2: api.payment.v1.MQJobInfo.created_at:type_name -> google.protobuf.Timestamp
	19, // 3: api.payment.v1.MQJobInfo.scheduled_at:type_name -> google.protobuf.Timestamp
	19, // 4: api.payment.v1.MQJobInfo.attempted_at:type_name -> google.protobuf.Timestamp
	19, // 5: api.payment.v1.MQJobInfo.finalized_at:type_name -> google.protobuf.Timestamp
	12, // 6: api.payment.v1.MQJobInfo.errors:type_name -> api.payment.v1.MQJobError
	19, // 7: api.payment.v1.MQJobError.at:type_name -> google.protobuf.Timestamp
	0,  // 8: api.payment.v1.QueryOrderReply.trade_state:type_name -> api.payment.v1.TradeState
	2,  // 9: api.payment.v1.Payment.CreatePayment:input_type -> api.payment.v1.CreatePaymentRequest
	3,  // 10: api.payment.v1.Payment.GetPayment:input_type -> api.payment.v1.GetPaymentRequest
	4,  // 11: api.payment.v1.Payment.GetPaymentByOrder:input_type -> api.payment.v1.GetPaymentByOrderRequest
	5,  // 12: api.payment.v1.Payment.NotifyPayment:input_type -> api.payment.v1.NotifyPaymentRequest
	7,  // 13: api.payment.v1.Payment.RefundPayment:input_type -> api.payment.v1.RefundPaymentRequest
	9,  // 14: api.payment.v1.Payment.CreateWechatPayCheckJob:input_type -> api.payment.v1.CreateWechatPayCheckJobRequest
	10, // 15: api.payment.v1.Payment.GetMQJob:input_type -> api.payment.v1.GetMQJobRequest
	13, // 16: api.payment.v1.WechatPayService.PrepayJSAPI:input_type -> api.payment.v1.PrepayJSAPIRequest
	15, // 17: api.payment.v1.WechatPayService.QueryOrder:input_type -> api.payment.v1.QueryOrderRequest
	17, // 18: api.payment.v1.WechatPayService.CloseOrder:input_type -> api.payment.v1.CloseOrderRequest
	1,  // 19: api.payment.v1.Payment.CreatePayment:output_type -> api.payment.v1.PaymentInfo
	1,  // 20: api.payment.v1.Payment.GetPayment:output_type -> api.payment.v1.PaymentInfo
	1,  // 21: api.payment.v1.Payment.GetPaymentByOrder:output_type -> api.payment.v1.PaymentInfo
	6,  // 22: api.payment.v1.Payment.NotifyPayment:output_type -> api.payment.v1.NotifyPaymentReply
	8,  // 23: api.payment.v1.Payment.RefundPayment:output_type -> api.payment.v1.RefundPaymentReply
	11, // 24: api.payment.v1.Payment.CreateWechatPayCheckJob:output_type -> api.payment.v1.MQJobInfo
	11, // 25: api.payment.v1.Payment.GetMQJob:output_type -> api.payment.v1.MQJobInfo
	14, // 26: api.payment.v1.WechatPayService.PrepayJSAPI:output_type -> api.payment.v1.PrepayJSAPIReply
	16, // 27: api.payment.v1.WechatPayService.QueryOrder:output_type -> api.payment.v1.QueryOrderReply
	18, // 28: api.payment.v1.WechatPayService.CloseOrder:output_type -> api.payment.v1.CloseOrderReply
	19, // [19:29] is the sub-list for method output_type
	9,  // [9:19] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_payment_v1_payment_proto_init() }
func file_api_payment_v1_payment_proto_init() {
	if File_api_payment_v1_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_payment_v1_payment_proto_rawDesc), len(file_api_payment_v1_payment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_payment_v1_payment_proto_goTypes,
		DependencyIndexes: file_api_payment_v1_payment_proto_depIdxs,
		EnumInfos:         file_api_payment_v1_payment_proto_enumTypes,
		MessageInfos:      file_api_payment_v1_payment_proto_msgTypes,
	}.Build()
	File_api_payment_v1_payment_proto = out.File
	file_api_payment_v1_payment_proto_goTypes = nil
	file_api_payment_v1_payment_proto_depIdxs = nil
}
