// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/payment/v1/payment.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId        int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId         int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MerchantId     int64                  `protobuf:"varint,4,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Amount         string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // pending/success/failed/refunded
	PayChannel     string                 `protobuf:"bytes,7,opt,name=pay_channel,json=payChannel,proto3" json:"pay_channel,omitempty"`
	ThirdPartyTxId string                 `protobuf:"bytes,8,opt,name=third_party_tx_id,json=thirdPartyTxId,proto3" json:"third_party_tx_id,omitempty"`
	PaidAt         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PaymentInfo) Reset() {
	*x = PaymentInfo{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentInfo) ProtoMessage() {}

func (x *PaymentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentInfo.ProtoReflect.Descriptor instead.
func (*PaymentInfo) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PaymentInfo) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *PaymentInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PaymentInfo) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *PaymentInfo) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *PaymentInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentInfo) GetPayChannel() string {
	if x != nil {
		return x.PayChannel
	}
	return ""
}

func (x *PaymentInfo) GetThirdPartyTxId() string {
	if x != nil {
		return x.ThirdPartyTxId
	}
	return ""
}

func (x *PaymentInfo) GetPaidAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PaidAt
	}
	return nil
}

func (x *PaymentInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MerchantId    int64                  `protobuf:"varint,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	PayChannel    string                 `protobuf:"bytes,4,opt,name=pay_channel,json=payChannel,proto3" json:"pay_channel,omitempty"` // wechat/alipay
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CreatePaymentRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreatePaymentRequest) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *CreatePaymentRequest) GetPayChannel() string {
	if x != nil {
		return x.PayChannel
	}
	return ""
}

type GetPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentRequest) Reset() {
	*x = GetPaymentRequest{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentRequest) ProtoMessage() {}

func (x *GetPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentRequest) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{2}
}

func (x *GetPaymentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPaymentByOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentByOrderRequest) Reset() {
	*x = GetPaymentByOrderRequest{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentByOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentByOrderRequest) ProtoMessage() {}

func (x *GetPaymentByOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentByOrderRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentByOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{3}
}

func (x *GetPaymentByOrderRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type NotifyPaymentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ThirdPartyTxId string                 `protobuf:"bytes,1,opt,name=third_party_tx_id,json=thirdPartyTxId,proto3" json:"third_party_tx_id,omitempty"`
	PayChannel     string                 `protobuf:"bytes,2,opt,name=pay_channel,json=payChannel,proto3" json:"pay_channel,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // success/failed
	PaymentId      int64                  `protobuf:"varint,4,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotifyPaymentRequest) Reset() {
	*x = NotifyPaymentRequest{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyPaymentRequest) ProtoMessage() {}

func (x *NotifyPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyPaymentRequest.ProtoReflect.Descriptor instead.
func (*NotifyPaymentRequest) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{4}
}

func (x *NotifyPaymentRequest) GetThirdPartyTxId() string {
	if x != nil {
		return x.ThirdPartyTxId
	}
	return ""
}

func (x *NotifyPaymentRequest) GetPayChannel() string {
	if x != nil {
		return x.PayChannel
	}
	return ""
}

func (x *NotifyPaymentRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NotifyPaymentRequest) GetPaymentId() int64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

type NotifyPaymentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` // "success" 告知第三方已处理
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyPaymentReply) Reset() {
	*x = NotifyPaymentReply{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyPaymentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyPaymentReply) ProtoMessage() {}

func (x *NotifyPaymentReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyPaymentReply.ProtoReflect.Descriptor instead.
func (*NotifyPaymentReply) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{5}
}

func (x *NotifyPaymentReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type RefundPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundPaymentRequest) Reset() {
	*x = RefundPaymentRequest{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundPaymentRequest) ProtoMessage() {}

func (x *RefundPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundPaymentRequest.ProtoReflect.Descriptor instead.
func (*RefundPaymentRequest) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{6}
}

func (x *RefundPaymentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RefundPaymentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundPaymentReply) Reset() {
	*x = RefundPaymentReply{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundPaymentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundPaymentReply) ProtoMessage() {}

func (x *RefundPaymentReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundPaymentReply.ProtoReflect.Descriptor instead.
func (*RefundPaymentReply) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{7}
}

var File_api_payment_v1_payment_proto protoreflect.FileDescriptor

const file_api_payment_v1_payment_proto_rawDesc = "" +
	"\n" +
	"\x1capi/payment/v1/payment.proto\x12\x0eapi.payment.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xde\x02\n" +
	"\vPaymentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vmerchant_id\x18\x04 \x01(\x03R\n" +
	"merchantId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1f\n" +
	"\vpay_channel\x18\a \x01(\tR\n" +
	"payChannel\x12)\n" +
	"\x11third_party_tx_id\x18\b \x01(\tR\x0ethirdPartyTxId\x123\n" +
	"\apaid_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x06paidAt\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x8c\x01\n" +
	"\x14CreatePaymentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\x03R\n" +
	"merchantId\x12\x1f\n" +
	"\vpay_channel\x18\x04 \x01(\tR\n" +
	"payChannel\"#\n" +
	"\x11GetPaymentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"5\n" +
	"\x18GetPaymentByOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\"\x99\x01\n" +
	"\x14NotifyPaymentRequest\x12)\n" +
	"\x11third_party_tx_id\x18\x01 \x01(\tR\x0ethirdPartyTxId\x12\x1f\n" +
	"\vpay_channel\x18\x02 \x01(\tR\n" +
	"payChannel\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x04 \x01(\x03R\tpaymentId\",\n" +
	"\x12NotifyPaymentReply\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"&\n" +
	"\x14RefundPaymentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x14\n" +
	"\x12RefundPaymentReply2\xde\x04\n" +
	"\aPayment\x12k\n" +
	"\rCreatePayment\x12$.api.payment.v1.CreatePaymentRequest\x1a\x1b.api.payment.v1.PaymentInfo\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/payments\x12g\n" +
	"\n" +
	"GetPayment\x12!.api.payment.v1.GetPaymentRequest\x1a\x1b.api.payment.v1.PaymentInfo\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/payments/{id}\x12\x81\x01\n" +
	"\x11GetPaymentByOrder\x12(.api.payment.v1.GetPaymentByOrderRequest\x1a\x1b.api.payment.v1.PaymentInfo\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/orders/{order_id}/payment\x12y\n" +
	"\rNotifyPayment\x12$.api.payment.v1.NotifyPaymentRequest\x1a\".api.payment.v1.NotifyPaymentReply\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/payments/notify\x12~\n" +
	"\rRefundPayment\x12$.api.payment.v1.RefundPaymentRequest\x1a\".api.payment.v1.RefundPaymentReply\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/payments/{id}/refundBM\n" +
	"\x0eapi.payment.v1P\x01Z9github.com/Dailiduzhou/simple-ecommerce/api/payment/v1;v1b\x06proto3"

var (
	file_api_payment_v1_payment_proto_rawDescOnce sync.Once
	file_api_payment_v1_payment_proto_rawDescData []byte
)

func file_api_payment_v1_payment_proto_rawDescGZIP() []byte {
	file_api_payment_v1_payment_proto_rawDescOnce.Do(func() {
		file_api_payment_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_payment_v1_payment_proto_rawDesc), len(file_api_payment_v1_payment_proto_rawDesc)))
	})
	return file_api_payment_v1_payment_proto_rawDescData
}

var file_api_payment_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_payment_v1_payment_proto_goTypes = []any{
	(*PaymentInfo)(nil),              // 0: api.payment.v1.PaymentInfo
	(*CreatePaymentRequest)(nil),     // 1: api.payment.v1.CreatePaymentRequest
	(*GetPaymentRequest)(nil),        // 2: api.payment.v1.GetPaymentRequest
	(*GetPaymentByOrderRequest)(nil), // 3: api.payment.v1.GetPaymentByOrderRequest
	(*NotifyPaymentRequest)(nil),     // 4: api.payment.v1.NotifyPaymentRequest
	(*NotifyPaymentReply)(nil),       // 5: api.payment.v1.NotifyPaymentReply
	(*RefundPaymentRequest)(nil),     // 6: api.payment.v1.RefundPaymentRequest
	(*RefundPaymentReply)(nil),       // 7: api.payment.v1.RefundPaymentReply
	(*timestamppb.Timestamp)(nil),    // 8: google.protobuf.Timestamp
}
var file_api_payment_v1_payment_proto_depIdxs = []int32{
	8, // 0: api.payment.v1.PaymentInfo.paid_at:type_name -> google.protobuf.Timestamp
	8, // 1: api.payment.v1.PaymentInfo.created_at:type_name -> google.protobuf.Timestamp
	1, // 2: api.payment.v1.Payment.CreatePayment:input_type -> api.payment.v1.CreatePaymentRequest
	2, // 3: api.payment.v1.Payment.GetPayment:input_type -> api.payment.v1.GetPaymentRequest
	3, // 4: api.payment.v1.Payment.GetPaymentByOrder:input_type -> api.payment.v1.GetPaymentByOrderRequest
	4, // 5: api.payment.v1.Payment.NotifyPayment:input_type -> api.payment.v1.NotifyPaymentRequest
	6, // 6: api.payment.v1.Payment.RefundPayment:input_type -> api.payment.v1.RefundPaymentRequest
	0, // 7: api.payment.v1.Payment.CreatePayment:output_type -> api.payment.v1.PaymentInfo
	0, // 8: api.payment.v1.Payment.GetPayment:output_type -> api.payment.v1.PaymentInfo
	0, // 9: api.payment.v1.Payment.GetPaymentByOrder:output_type -> api.payment.v1.PaymentInfo
	5, // 10: api.payment.v1.Payment.NotifyPayment:output_type -> api.payment.v1.NotifyPaymentReply
	7, // 11: api.payment.v1.Payment.RefundPayment:output_type -> api.payment.v1.RefundPaymentReply
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_payment_v1_payment_proto_init() }
func file_api_payment_v1_payment_proto_init() {
	if File_api_payment_v1_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_payment_v1_payment_proto_rawDesc), len(file_api_payment_v1_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_payment_v1_payment_proto_goTypes,
		DependencyIndexes: file_api_payment_v1_payment_proto_depIdxs,
		MessageInfos:      file_api_payment_v1_payment_proto_msgTypes,
	}.Build()
	File_api_payment_v1_payment_proto = out.File
	file_api_payment_v1_payment_proto_goTypes = nil
	file_api_payment_v1_payment_proto_depIdxs = nil
}
